import type { KnowledgeVerificationStatus } from "@/lib/knowledge/source/types";

export type PackStatus = "draft" | "in_review" | "reviewed" | "verification_pending" | "verified" | "published" | "archived" | "rejected";
export interface AuthoringProvenance { sourceId: string; sourceType: "curriculum" | "textbook" | "teacherGuide" | "officialReference" | "internalOriginal"; title: string; publisher?: string; edition?: string; pageRange?: string; documentId?: string; chunkId?: string; note?: string; verificationStatus: KnowledgeVerificationStatus; reviewedBy?: string; reviewedAt?: string; evidenceSummary?: string; }
export interface DefinitionSet { easy: string; standard: string; precise: string; }
export interface ExplanationMaterial { id: string; strategy: "definition" | "comparison" | "contrast" | "analogy" | "step_by_step" | "rule_discovery" | "direct_application" | "teacher_feedback"; content: string; difficulty: 1 | 2 | 3 | 4 | 5; provenanceIds: string[]; status: PackStatus; }
export interface AuthoringExample { exampleId: string; sentence: string; focus: string; analysis: string; explanation: string; difficulty: 1 | 2 | 3 | 4 | 5; strategyTags: string[]; allowedLevels: number[]; sourceStatus: PackStatus; isOriginal: boolean; provenanceIds: string[]; }
export interface Counterexample { counterexampleId: string; sentence: string; expectedJudgment: string; reason: string; confusionTarget: string; provenanceIds: string[]; }
export interface AuthoringMisconception { misconceptionId: string; description: string; likelyResponses: string[]; correctionStrategy: string; correctiveExamples: string[]; prerequisiteHint: string; severity: 1 | 2 | 3; provenanceIds: string[]; }
export interface AuthoringCheck { checkId: string; type: "choice" | "short_answer" | "application" | "explanation"; prompt: string; options: string[]; correctAnswer: string; acceptedPatterns: string[]; explanation: string; difficulty: 1 | 2 | 3 | 4 | 5; evidenceRequired: boolean; provenanceIds: string[]; }
export interface AuthoringWorkedExample { workedExampleId: string; question: string; steps: string[]; answer: string; explanation: string; transferableRule: string; provenanceIds: string[]; }
export interface AuthoringFaq { question: string; answer: string; provenanceIds: string[]; }
export interface AuthoringTeacherStrategy { purpose: string; strategy: string; caution: string; provenanceIds: string[]; }
export interface AuthoringEvaluationPoint { criterion: string; evidence: string; commonError: string; provenanceIds: string[]; }
export interface AuthoringConcept { conceptId: string; title: string; aliases: string[]; summary: string; definition: DefinitionSet; coreUnderstanding: string[]; learningObjectives: string[]; scope: string; prerequisites: string[]; nextConcepts: string[]; relatedConcepts: string[]; discriminationRules: string[]; comparisonTargets: string[]; completionCriteria: string[]; difficulty: 1 | 2 | 3 | 4 | 5; tags: string[]; explanations: ExplanationMaterial[]; examples: AuthoringExample[]; counterexamples: Counterexample[]; misconceptions: AuthoringMisconception[]; checks: AuthoringCheck[]; workedExamples: AuthoringWorkedExample[]; provenanceIds: string[]; decisionProcedure?: string[]; faq?: AuthoringFaq[]; teacherStrategies?: AuthoringTeacherStrategy[]; studentQuestions?: string[]; evaluationPoints?: AuthoringEvaluationPoint[]; }
export interface AuthoringKnowledgePack { packId: string; title: string; subject: "국어"; domain: "문법"; curriculumYear: string; schoolLevel: "middle"; gradeRange: number[]; semester: string; version: string; schemaVersion: 2; status: PackStatus; createdAt: string; updatedAt: string; note: string; provenance: AuthoringProvenance[]; concepts: AuthoringConcept[]; }
export interface AuthoringIssue { severity: "error" | "warning" | "info"; code: string; path: string; message: string; }
export interface AuthoringValidation { valid: boolean; issues: AuthoringIssue[]; }
export interface ConceptCoverage { conceptId: string; score: number; roles: Record<string, { current: number; required: number; complete: boolean }>; }
export interface RawSourceChunk { sourceId: string; documentId: string; pageRange: string; heading: string; rawText: string; normalizedText: string; extractionMethod: string; confidence: number; note?: string; }
export interface RawImportDraft { sourceId: string; status: "draft"; candidateDefinitions: string[]; candidateRules: string[]; candidateExamples: string[]; candidateMisconceptions: string[]; reviewQueue: string[]; }
