"use client";
import { useEffect, useMemo, useState } from "react";
import { approvePage, cancelNormalizedPageEdit, completeWizardReview, createImportWizardState, createWizardCandidate, createWizardDraft, createWizardReviewQueue, decideWizardReview, editNormalizedPage, extractFixture, mergeChunks, moveWizard, rebuildChunks, repairFixtureCoverage, requestWizardVerification, resolveWizardConflict, selectFixture, splitChunk, startWizardReview, updateChunk, updateImportMetadata, validateWizardDraft, verifyWizardPack, wizardProgress } from "@/lib/knowledge/importWizard/importWizardEngine";
import { clearImportWizard, loadImportWizard, saveImportWizard } from "@/lib/knowledge/importWizard/storage";
import type { ImportWizardState, ImportWizardStep } from "@/lib/knowledge/importWizard/types";

const names = ["파일 선택", "문서 정보", "추출", "페이지 검토", "Chunk 검토", "Review Queue", "Pack Draft", "검증", "Review·Verification 준비", "Release Candidate"];
const button = "rounded border border-zinc-300 bg-white px-3 py-2 text-sm hover:bg-zinc-50 focus:outline-none focus:ring-2 focus:ring-black disabled:opacity-40";
export default function ImportClient() {
  const [state, setState] = useState<ImportWizardState>(() => createImportWizardState()), [hydrated, setHydrated] = useState(false), [notice, setNotice] = useState(""), [pageIndex, setPageIndex] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => { const saved = loadImportWizard(localStorage); if (saved) { setState(saved); setNotice("마지막 작업을 복원했습니다."); } setHydrated(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!hydrated) return; const timer = window.setTimeout(() => saveImportWizard(localStorage, state), 250); return () => window.clearTimeout(timer); }, [hydrated, state]);
  const progress = useMemo(() => wizardProgress(state), [state]);
  function go(step: ImportWizardStep) { const result = moveWizard(state, step); setState(result.state); setNotice(result.reason ? `이동할 수 없습니다: ${result.reason}` : ""); }
  function reset() { if (!window.confirm("현재 Import 작업을 모두 지우고 새 문서를 시작할까요?")) return; clearImportWizard(localStorage); setState(createImportWizardState()); setNotice("새 문서 작업을 시작합니다."); }
  const currentPage = state.extractedPages[pageIndex], firstChunk = state.chunks[0], secondChunk = state.chunks[1];
  return <main className="min-h-screen bg-zinc-100 px-4 py-6 text-black"><div className="mx-auto max-w-6xl">
    <p className="text-sm font-semibold text-zinc-600">Development only · Local fixture</p><h1 className="mt-1 text-3xl font-bold">교육 콘텐츠 Import Wizard</h1>
    <nav className="mt-3 flex flex-wrap gap-2 text-sm" aria-label="관련 개발 화면">{[["Sources", "/dev/sources"], ["Knowledge", "/dev/knowledge"], ["Releases", "/dev/releases"], ["Readiness", "/dev/readiness"]].map(([label, href]) => <a key={href} className="underline" href={href} target="_blank" rel="noreferrer">{label}</a>)}</nav>
    <section className="mt-4 rounded-xl bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-zinc-500">Step {state.currentStep}/10</p><h2 className="text-xl font-bold">{names[state.currentStep - 1]}</h2></div><div className="text-right text-sm"><p>전체 진행률 {progress.overall}%</p><p>{state.dirty ? "저장 대기" : state.lastSavedAt ? "저장됨" : "새 작업"} · 오류 {state.errors.length}개</p></div></div>
      <div className="mt-3 h-2 overflow-hidden rounded bg-zinc-200"><div className="h-full bg-black" style={{ width: `${progress.overall}%` }} /></div>
      <div className="mt-3 grid gap-1 text-xs sm:grid-cols-5"><span>페이지 {state.approvedPageNumbers.length}/{state.extractedPages.length}</span><span>Chunk {state.chunks.filter(({ status }) => status === "reviewed" || status === "rejected").length}/{state.chunks.length}</span><span>Review {state.reviewItems.filter(({ status }) => status !== "pending").length}/{state.reviewItems.length}</span><span>Coverage {Math.round(progress.coverage * 100)}%</span><span>Checklist {Math.round(progress.checklist * 100)}%</span></div>
    </section>
    {notice && <p className="mt-3 rounded bg-amber-50 p-3 text-sm" role="status">{notice}</p>}
    <section className="mt-4 rounded-xl bg-white p-4">{state.currentStep === 1 && <div><button className={button} onClick={() => setState(selectFixture(state))} aria-label="자체 제작 fixture PDF 선택">Fixture PDF 선택·검증</button>{state.fileInspection && <dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div>파일명: {state.fileInspection.fileName}</div><div>MIME: {state.fileInspection.mimeType}</div><div>크기: {state.fileInspection.fileSize} bytes</div><div>페이지: {state.fileInspection.pageCount}</div><div>checksum: {state.fileInspection.checksum}</div><div>암호화: {state.fileInspection.encrypted ? "예" : "아니요"}</div><div>추출 가능: {state.fileInspection.extractable ? "예" : "아니요"}</div><div>오류: {state.fileInspection.errors.join(", ") || "없음"}</div></dl>}</div>}
      {state.currentStep === 2 && <div className="grid gap-3 sm:grid-cols-2">{[["title", "제목"], ["publisher", "발행자"], ["edition", "판"], ["curriculumYear", "교육과정 연도"], ["domain", "영역"], ["semester", "학기"], ["note", "메모"]].map(([key, label]) => <label key={key} className="text-sm">{label}<input className="mt-1 w-full rounded border p-2" value={String(state.metadata[key as keyof typeof state.metadata] ?? "")} onChange={(event) => setState(updateImportMetadata(state, { [key]: event.target.value }))} /></label>)}</div>}
      {state.currentStep === 3 && <div><button className={button} onClick={async () => setState(await extractFixture(state))} aria-label="페이지 텍스트 추출 시작">추출 시작·재시도</button><button className={`${button} ml-2`} onClick={() => setState({ ...state, sourceDocument: null, extractedPages: [], chunks: [] })}>추출 결과 초기화</button><p className="mt-3 text-sm">상태: {state.sourceDocument?.extractionStatus ?? "대기"}</p>{state.extractedPages.map((page) => <p key={page.pageNumber} className="mt-1 text-sm">{page.pageNumber}쪽 · confidence {page.extractionConfidence} · {page.warnings.join(", ") || "warning 없음"}</p>)}</div>}
      {state.currentStep === 4 && currentPage && <div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2 flex items-center justify-between"><button className={button} disabled={pageIndex === 0} onClick={() => setPageIndex((value) => value - 1)}>이전 페이지</button><strong>{currentPage.pageNumber}/{state.extractedPages.length}쪽</strong><button className={button} disabled={pageIndex >= state.extractedPages.length - 1} onClick={() => setPageIndex((value) => value + 1)}>다음 페이지</button></div><label className="text-sm">원문(rawText, 읽기 전용)<textarea readOnly className="mt-1 h-64 w-full resize-none overflow-auto rounded border bg-zinc-100 p-2" value={currentPage.rawText} /></label><label className="text-sm">정규화 결과<textarea className="mt-1 h-64 w-full overflow-auto rounded border p-2" value={currentPage.normalizedText} onChange={(event) => setState(editNormalizedPage(state, currentPage.pageNumber, event.target.value))} /></label><div className="md:col-span-2 flex flex-wrap gap-2"><button className={button} onClick={() => setState(cancelNormalizedPageEdit(state, currentPage.pageNumber))}>수정 취소</button>{state.extractedPages.map((page) => <button key={page.pageNumber} className={button} onClick={() => setState(approvePage(state, page.pageNumber))}>{page.pageNumber}쪽 승인</button>)}</div></div>}
      {state.currentStep === 5 && <div><button className={button} onClick={() => setState(rebuildChunks(state))}>Chunk 생성·검토 완료</button>{firstChunk && <div className="mt-3 flex flex-wrap gap-2"><button className={button} onClick={() => setState(splitChunk(state, firstChunk.chunkId))}>첫 Chunk 분할</button>{secondChunk && <button className={button} onClick={() => setState(mergeChunks(state, firstChunk.chunkId, secondChunk.chunkId))}>인접 Chunk 병합</button>}<button className={button} onClick={() => setState(updateChunk(state, firstChunk.chunkId, { status: "rejected", candidateTypes: ["irrelevant"] }))}>irrelevant 처리</button></div>}{state.chunks.map((chunk) => <article key={chunk.chunkId} className="mt-3 rounded border p-3 text-sm"><p className="font-semibold">{chunk.heading || "제목 없음"} · {chunk.pageRange}쪽 · {chunk.tokenEstimate} tokens</p><p className="mt-1">{chunk.normalizedText}</p><p className="mt-1 text-xs text-zinc-500">{chunk.candidateTypes.join(", ")} · {chunk.status} · {chunk.reason.join(", ")}</p></article>)}</div>}
      {state.currentStep === 6 && <div><button className={button} onClick={() => setState(createWizardReviewQueue(state))}>Review Queue 생성</button>{state.reviewItems.map((item) => <article key={item.reviewItemId} className="mt-3 rounded border p-3 text-sm"><p>{item.proposedContent}</p><p className="mt-1 text-xs">concept: {item.proposedConceptIds.join(", ")} · source {item.pageRange}쪽 · {item.status}</p><div className="mt-2 flex flex-wrap gap-2">{(["accepted", "edited", "rejected", "deferred"] as const).map((decision) => <button key={decision} className={button} onClick={() => setState(decideWizardReview(state, item.reviewItemId, decision, `${decision} 검토`))}>{decision}</button>)}</div></article>)}</div>}
      {state.currentStep === 7 && <div><button className={button} onClick={() => setState(createWizardDraft(state).state)}>Pack Draft 생성</button><p className="mt-3 text-sm">concept {state.draftPack?.concepts.length ?? 0}개 · provenance {state.draftPack?.provenance.length ?? 0}개 · conflict {state.conflicts.length}개</p>{state.conflicts.map((conflict) => <article key={conflict.conflictId} className="mt-2 rounded border border-amber-300 p-3 text-sm"><p>{conflict.conceptId} · {conflict.field} · {conflict.status}</p><button className={`${button} mt-2`} onClick={() => setState(resolveWizardConflict(state, conflict.conflictId, "existing"))}>기존 내용 유지로 해결</button></article>)}</div>}
      {state.currentStep === 8 && <div className="flex flex-wrap gap-2"><button className={button} onClick={() => setState(validateWizardDraft(state))}>재검증</button><button className={button} onClick={() => setState(validateWizardDraft(repairFixtureCoverage(state)))}>Fixture coverage 보완·검증</button><div className="w-full">{state.validationResult?.issues.map((issue, index) => <p key={`${issue.code}-${index}`} className="mt-1 text-sm">{issue.severity} · {issue.code} · {issue.path}</p>)}{state.coverageResult.map((item) => <p key={item.conceptId} className="mt-1 text-sm">{item.conceptId}: {item.score}%</p>)}</div></div>}
      {state.currentStep === 9 && <div className="flex flex-wrap gap-2"><button className={button} onClick={() => { const result = startWizardReview(state); setState(result.state); setNotice(result.reason); }}>in_review 전환</button><button className={button} onClick={() => { const result = completeWizardReview(state); setState(result.state); setNotice(result.reason); }}>Checklist 완료·reviewed</button><button className={button} onClick={() => { const result = requestWizardVerification(state); setState(result.state); setNotice(result.reason); }}>verification 요청</button><button className={button} onClick={() => { const result = verifyWizardPack(state); setState(result.state); setNotice(result.reason); }}>verified 전환</button><p className="mt-3 w-full text-sm">Pack status: {state.reviewState?.status ?? state.draftPack?.status ?? "없음"} · checklist {state.reviewState?.checklists.filter(({ completed }) => completed).length ?? 0}/{state.reviewState?.checklists.length ?? 0} · conflict {state.conflicts.filter(({ status }) => status === "unresolved").length}</p></div>}
      {state.currentStep === 10 && <div><div className="mb-3 grid gap-2 rounded bg-zinc-100 p-3 text-sm sm:grid-cols-2"><p>제안 version: {state.reviewState?.pack.version ?? "확인 필요"}</p><p>변경 유형: fixture 신규 Release</p><p>Retrieval smoke: {state.reviewState?.status === "verified" ? "준비됨" : "대기"}</p><p>Mock Conversation smoke: {state.reviewState?.status === "verified" ? "준비됨" : "대기"}</p></div><label className="text-sm">Release notes<textarea className="mt-1 h-24 w-full rounded border p-2" value={state.releaseNotes} onChange={(event) => setState({ ...state, releaseNotes: event.target.value })} /></label><button className={`${button} mt-2`} onClick={() => { const result = createWizardCandidate(state); setState(result.state); setNotice(result.reason); }}>Candidate 생성</button>{state.releaseCandidate && <pre className="mt-3 max-h-96 overflow-auto rounded bg-zinc-900 p-3 text-xs text-white">{JSON.stringify(state.releaseCandidate, null, 2)}</pre>}</div>}
    </section>
    <footer className="sticky bottom-0 mt-4 flex items-center justify-between gap-2 rounded-xl border bg-white p-3"><button className={button} disabled={state.currentStep === 1} onClick={() => go((state.currentStep - 1) as ImportWizardStep)} aria-label="이전 단계">이전</button><div className="flex gap-2"><button className={button} onClick={() => saveImportWizard(localStorage, state)}>현재 단계 저장</button><button className={button} onClick={reset}>전체 초기화·새 문서</button><button className={button} disabled={state.currentStep === 10} onClick={() => go((state.currentStep + 1) as ImportWizardStep)} aria-label="다음 단계">다음</button></div></footer>
  </div></main>;
}
