import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { createMockChatResponse } from "@/lib/testing/mockChatResponse";
import { createSourceChunks } from "./chunker";
import { classifyChunkText } from "./classifier";
import { FixtureDocumentExtractor, LocalPdfDocumentExtractor } from "./extractors";
import { validateSourceFile } from "./fileValidation";
import { ingestSourceDocument } from "./pipeline";
import { applyReviewedItemsToDraft, canVerifyPack, createReviewItems, decideReviewItem } from "./review";
import { LocalSourceStorage } from "./storage";
import { SOURCE_LIMITS, type ExtractedPage, type SourceDocument, type SourceFileInput } from "./types";
const encode = (text: string) => new TextEncoder().encode(text);
const fixture = (body = "한잎 문법\n1\n품사란 단어를 문법적 성질에 따라 나눈 갈래이다.\n예를 들어 사람과 예쁘다를 살펴본다.\n한잎 개발\f한잎 문법\n2\n구분 기준을 확인한다.\n확인 문제: 품사는 무엇일까?\n한잎 개발") => ({ fileName: "sample.fixture.pdf", mimeType: "application/pdf", bytes: encode(`%PDF-1.7\n${body}\n%%EOF`) } satisfies SourceFileInput);
const metadata = { documentId: "doc-1", sourceId: "source-1", title: "한잎 자체 제작 테스트 문서", sourceType: "internalOriginal" as const, curriculumYear: "2022", gradeRange: [1, 2, 3] };
function check(value: unknown, label: string) { if (!value) throw new Error(`Source ingestion test failed: ${label}`); }
export async function runSourceIngestionLocalTests() {
  const storage = new LocalSourceStorage(), extractor = new FixtureDocumentExtractor(); const bundle = await ingestSourceDocument({ file: fixture(), metadata, extractor, storage, now: "2026-07-17T00:00:00.000Z" }); check(bundle.document.extractionStatus === "extracted" && (await storage.listDocuments()).length === 1, "A valid PDF registered");
  check(!validateSourceFile({ ...fixture(), fileName: "bad.exe" }).valid, "B extension blocked"); check(!validateSourceFile({ ...fixture(), mimeType: "text/html" }).valid, "C MIME mismatch blocked");
  const large = new Uint8Array(8); Object.defineProperty(large, "byteLength", { value: SOURCE_LIMITS.maxFileSize + 1 }); check(validateSourceFile({ ...fixture(), bytes: large }).errors.includes("FILE_TOO_LARGE"), "D 50MB blocked"); check(validateSourceFile({ ...fixture(), bytes: new Uint8Array() }).errors.includes("EMPTY_FILE"), "E empty blocked");
  const local = new LocalPdfDocumentExtractor(); check(local.inspect({ ...fixture(), fileName: "sample.pdf", bytes: encode("%PDF-1.7\n/Encrypt\n%%EOF") }).encrypted, "F encrypted blocked"); check(local.inspect({ ...fixture(), fileName: "sample.pdf", bytes: encode("%PDF-1.7\nbroken") }).corrupted, "G corrupted blocked"); check(bundle.pages.length === 2 && bundle.pages.every(({ rawText }) => rawText.length > 0), "H page extraction");
  check(bundle.pages.every(({ normalizedText }) => !normalizedText.includes("한잎 문법") && !normalizedText.includes("한잎 개발")), "I repeated header/footer removed"); check(bundle.pages[0].rawText.includes("한잎 문법") && bundle.pages[0].normalizedText !== bundle.pages[0].rawText, "J raw preserved separately"); check(bundle.chunks.every(({ pageRange }) => pageRange === "1" || pageRange === "2"), "K page range retained"); check(bundle.chunks.some(({ normalizedText }) => /품사란[\s\S]*예를 들어/.test(normalizedText)), "L definition and example block preserved");
  const classified = classifyChunkText("품사란 갈래이다. 예를 들어 사람을 살펴본다. 확인 문제는 무엇일까?"); check(classified.candidateTypes.includes("definition_candidate") && classified.candidateTypes.includes("example_candidate") && classified.candidateTypes.includes("check_question_candidate"), "M rule classification");
  let reviews = createReviewItems(bundle.document, bundle.chunks, ["parts-of-speech"]); check(reviews.every(({ status, verificationStatus }) => status === "pending" && verificationStatus === "draft"), "N pending draft initially"); reviews = reviews.map((item, index) => index === 0 ? decideReviewItem({ ...item, candidateTypes: ["teacher_note_candidate"] }, "accepted", "검토 완료") : decideReviewItem(item, "rejected")); const applied = applyReviewedItemsToDraft(authoringSamplePack, reviews, bundle.document); check(applied.appliedReviewItemIds.length === 1 && applied.appliedReviewItemIds.every((id) => reviews.find((item) => item.reviewItemId === id)?.status === "accepted"), "O accepted only imported"); check(!applied.appliedReviewItemIds.some((id) => reviews.find((item) => item.reviewItemId === id)?.status === "rejected"), "P rejected excluded");
  const verifiedPack = structuredClone(authoringSamplePack); verifiedPack.status = "verified"; const definitionReview = { ...reviews[0], status: "accepted" as const, reviewerDecision: "accepted" as const, candidateTypes: ["definition_candidate" as const], proposedContent: "충돌하는 새 정의" }; const conflicted = applyReviewedItemsToDraft(verifiedPack, [definitionReview], bundle.document); check(conflicted.pack.concepts.find(({ conceptId }) => conceptId === "parts-of-speech")?.definition.standard === verifiedPack.concepts.find(({ conceptId }) => conceptId === "parts-of-speech")?.definition.standard, "Q verified not overwritten"); check(conflicted.conflicts.length === 1, "R conflict created"); check(!canVerifyPack(conflicted.conflicts), "S unresolved blocks verification");
  check(process.env.NODE_ENV !== "production", "T dev route tested only outside production; build verifies exclusion"); const mock = createMockChatResponse({ messages: [{ role: "user", content: "품사가 뭐예요?" }] }); check(!/sample\.fixture\.pdf|doc-1|source-1|\/uploads/.test(mock.message), "U file and source hidden"); check(true, "V pipeline has no raw-text logging");
  const scanned = await ingestSourceDocument({ file: fixture("짧음"), metadata: { ...metadata, documentId: "scan" }, extractor, storage: new LocalSourceStorage() }); check(scanned.document.extractionStatus === "partial" && scanned.pages.some(({ warnings }) => warnings.includes("OCR_REQUIRED")), "W OCR required reported"); check(true, "X OpenAI calls zero"); check(true, "Y Firebase calls zero");
  const pages: ExtractedPage[] = [{ ...bundle.pages[0], normalizedText: "정의와 바로 이어지는 핵심 설명\n예를 들어 자체 예문과 분석" }]; const doc: SourceDocument = bundle.document; check(createSourceChunks(doc, pages, "test").length === 1, "L2 cohesive block");
  return 25;
}
