import { classifyChunks } from "./classifier";
import { validateSourceFile } from "./fileValidation";
import type { DocumentExtractor, ExtractionBundle, SourceDocument, SourceFileInput, SourceStorage, SourceType } from "./types";
export async function ingestSourceDocument(input: { file: SourceFileInput; metadata: { documentId: string; sourceId: string; title: string; sourceType: SourceType; publisher?: string; edition?: string; curriculumYear: string; gradeRange: number[] }; extractor: DocumentExtractor; storage: SourceStorage; now?: string }): Promise<ExtractionBundle> {
  const validation = validateSourceFile(input.file); if (!validation.valid) throw new Error(validation.errors.join(",")); if (!input.extractor.canHandle(input.file)) throw new Error("UNSUPPORTED_DOCUMENT"); const inspected = input.extractor.inspect(input.file); if (!inspected.valid) throw new Error(inspected.encrypted ? "ENCRYPTED_PDF" : inspected.corrupted ? "CORRUPTED_PDF" : inspected.warnings.join(","));
  const now = input.now ?? new Date().toISOString(); const document: SourceDocument = { ...input.metadata, schoolLevel: "middle", subject: "국어", uploadedFileName: validation.safeFileName, mimeType: input.file.mimeType, fileSize: input.file.bytes.byteLength, pageCount: inspected.pageCount, checksum: checksum(input.file.bytes), extractionStatus: "extracting", reviewStatus: "unreviewed", createdAt: now, updatedAt: now };
  await input.storage.saveOriginal(document, input.file.bytes); const rawPages = await input.extractor.extractPages(document, input.file); const pages = input.extractor.normalizePages(rawPages); const ocrRequired = pages.some(({ warnings }) => warnings.includes("OCR_REQUIRED")); document.extractionStatus = ocrRequired ? "partial" : "extracted"; document.updatedAt = now; const chunks = classifyChunks(input.extractor.createChunks(document, pages)); const bundle = { document, pages, chunks }; await input.storage.saveExtraction(bundle); return bundle;
}
function checksum(bytes: Uint8Array) { let hash = 2166136261; for (const value of bytes) hash = Math.imul(hash ^ value, 16777619); return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
