import type { AuthoringKnowledgePack, AuthoringProvenance } from "@/lib/knowledge/authoring/types";
import type { ContentConflict, IngestionSourceChunk, PackDraftApplyResult, ReviewDecision, ReviewItem, SourceDocument } from "./types";
export function createReviewItems(document: SourceDocument, chunks: IngestionSourceChunk[], conceptIds: string[] = []): ReviewItem[] { const now = "2026-07-17T00:00:00.000Z"; return chunks.filter(({ candidateTypes }) => !candidateTypes.every((type) => type === "irrelevant")).map((chunk, index) => ({ reviewItemId: `${document.documentId}-review-${index + 1}`, documentId: document.documentId, chunkId: chunk.chunkId, sourceId: document.sourceId, pageRange: chunk.pageRange, candidateTypes: chunk.candidateTypes, proposedConceptIds: conceptIds, proposedContent: chunk.normalizedText, reviewerDecision: "pending", reviewerNote: "", status: "pending", verificationStatus: "draft", createdAt: now, updatedAt: now })); }
export function decideReviewItem(item: ReviewItem, decision: Exclude<ReviewDecision, "pending">, note = "", editedContent?: string): ReviewItem { return { ...item, proposedContent: decision === "edited" && editedContent ? editedContent : item.proposedContent, reviewerDecision: decision, status: decision, reviewerNote: note, updatedAt: new Date().toISOString() }; }
export function applyReviewedItemsToDraft(pack: AuthoringKnowledgePack, items: ReviewItem[], document: SourceDocument): PackDraftApplyResult {
  const next = structuredClone(pack), conflicts: ContentConflict[] = [], appliedReviewItemIds: string[] = [];
  const accepted = items.filter(({ status }) => status === "accepted" || status === "edited");
  const provenance: AuthoringProvenance = { sourceId: document.sourceId, sourceType: document.sourceType, title: document.title, publisher: document.publisher, edition: document.edition, documentId: document.documentId, verificationStatus: "draft", note: "사람 검토를 통과한 초안 후보" };
  if (!next.provenance.some(({ sourceId }) => sourceId === provenance.sourceId)) next.provenance.push(provenance);
  for (const item of accepted) for (const conceptId of item.proposedConceptIds) { const concept = next.concepts.find((value) => value.conceptId === conceptId); if (!concept) continue; const isDefinition = item.candidateTypes.includes("definition_candidate"); const existing = concept.definition.standard;
    if (isDefinition && existing && existing !== item.proposedContent) { conflicts.push({ conflictId: `${item.reviewItemId}-definition`, conceptId, field: "definition.standard", existingValue: existing, proposedValue: item.proposedContent, existingSources: concept.provenanceIds, proposedSources: [document.sourceId], severity: next.status === "verified" ? "high" : "medium", status: "unresolved", reviewerNote: item.reviewerNote }); continue; }
    concept.explanations.push({ id: `${item.reviewItemId}-draft`, strategy: isDefinition ? "definition" : "teacher_feedback", content: item.proposedContent, difficulty: 2, provenanceIds: [document.sourceId], status: "draft" }); concept.provenanceIds = [...new Set([...concept.provenanceIds, document.sourceId])]; appliedReviewItemIds.push(item.reviewItemId);
  }
  next.status = "draft"; next.updatedAt = new Date().toISOString(); return { pack: next, appliedReviewItemIds: [...new Set(appliedReviewItemIds)], conflicts };
}
export function canVerifyPack(conflicts: ContentConflict[]) { return !conflicts.some(({ status }) => status === "unresolved"); }
