"use client";
import { useMemo, useState } from "react";
import { calculateConceptCoverage } from "@/lib/knowledge/authoring/coverage";
import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { ActiveReleaseRegistry, completeChecklist, createAuditEvent, createPackWorkflow, createReleaseCandidate, publishRelease, transitionPack } from "@/lib/knowledge/release/releaseEngine";
import type { KnowledgeAuditEvent, KnowledgePackRelease, PackWorkflow, ReleaseActor } from "@/lib/knowledge/release/types";
const author: ReleaseActor = { actorId: "dev-author", role: "author" }, reviewer: ReleaseActor = { actorId: "dev-reviewer", role: "reviewer" }, verifier: ReleaseActor = { actorId: "dev-verifier", role: "verifier" }, publisher: ReleaseActor = { actorId: "dev-publisher", role: "publisher" }, administrator: ReleaseActor = { actorId: "dev-admin", role: "administrator" };
const registry = new ActiveReleaseRegistry();
export default function ReleasesClient() {
  const [workflow, setWorkflow] = useState<PackWorkflow>(() => createPackWorkflow(authoringSamplePack, author.actorId)); const [candidate, setCandidate] = useState<KnowledgePackRelease | null>(null), [published, setPublished] = useState<KnowledgePackRelease[]>([]), [audit, setAudit] = useState<KnowledgeAuditEvent[]>([]), [notice, setNotice] = useState("");
  const coverage = useMemo(() => workflow.pack.concepts.map(calculateConceptCoverage), [workflow]);
  function log(action: string, previous: string, next: string, actor: ReleaseActor) { setAudit((items) => [...items, createAuditEvent({ actorId: actor.actorId, actorRole: actor.role, action, targetType: "pack", targetId: workflow.pack.packId, previousStatus: previous, nextStatus: next, changedFields: ["status"], reason: "개발용 fixture workflow" })]); }
  function move(next: Parameters<typeof transitionPack>[1], actor: ReleaseActor) { const result = transitionPack(workflow, next, actor); setNotice(result.success ? `${workflow.status} → ${next}` : result.reason); if (result.success) { log("status_transition", workflow.status, next, actor); setWorkflow(result.workflow); } }
  function finishReview() { const next = structuredClone(workflow); next.checklists = next.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, reviewer.actorId)); setWorkflow(next); setNotice("모든 concept checklist를 pass 처리했습니다."); }
  function prepareVerification() { const next = structuredClone(workflow); next.pack.provenance = next.pack.provenance.map((item) => ({ ...item, verificationStatus: "reviewed", reviewedBy: reviewer.actorId, reviewedAt: new Date().toISOString() })); next.pack.concepts = next.pack.concepts.map((concept) => ({ ...concept, explanations: concept.explanations.map((item) => ({ ...item, status: "reviewed" })), examples: concept.examples.map((item) => ({ ...item, sourceStatus: "reviewed" })) })); setWorkflow(next); setNotice("검증 대기 자료 상태를 준비했습니다."); }
  function makeCandidate() { try { const value = createReleaseCandidate(workflow, publisher, "개발용 fixture release candidate"); setCandidate(value); setNotice(`Candidate ${value.releaseId} 생성`); } catch (error) { setNotice(error instanceof Error ? error.message : "Candidate 생성 실패"); } }
  function publish() { if (!candidate) return; const value = publishRelease(candidate, publisher); registry.register(value); setPublished((items) => [...items, value]); setCandidate(null); setNotice(`Published ${value.releaseId}`); }
  function activate(id: string) { const result = registry.activate(id, publisher); setNotice(result.success ? `Active ${id}` : result.reason); }
  function rollback() { const result = registry.rollback(administrator); setNotice(result.success ? `Rollback ${result.active?.activeReleaseId ?? "완료"}` : (result.reason ?? "Rollback 실패")); }
  return <main className="min-h-screen bg-zinc-100 px-4 py-8 text-black"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-zinc-600">Development only</p><h1 className="mt-1 text-3xl font-bold">Knowledge Review · Release</h1><p className="mt-2 text-sm">고정 내부 사용자와 자체 제작 fixture만 사용하는 발행 검증 화면입니다.</p>{notice && <p className="mt-3 rounded bg-white p-3 text-sm" role="status">{notice}</p>}
  <section className="mt-5 grid gap-3 rounded-xl bg-white p-4 text-sm md:grid-cols-4"><p>Pack <strong>{workflow.pack.title}</strong></p><p>Status <strong>{workflow.status}</strong></p><p>Conflict <strong>{workflow.conflicts.filter(({ status }) => status === "unresolved").length}</strong></p><p>Active <strong>{registry.getActive()?.activeReleaseId ?? "없음"}</strong></p></section>
  <div className="mt-5 flex flex-wrap gap-2"><button className="rounded bg-black px-3 py-2 text-white" onClick={() => move("in_review", author)}>Review 요청</button><button className="rounded border bg-white px-3 py-2" onClick={finishReview}>Checklist 완료</button><button className="rounded border bg-white px-3 py-2" onClick={() => move("reviewed", reviewer)}>reviewed 전환</button><button className="rounded border bg-white px-3 py-2" onClick={prepareVerification}>검증 자료 준비</button><button className="rounded border bg-white px-3 py-2" onClick={() => move("verification_pending", verifier)}>검증 요청</button><button className="rounded border bg-white px-3 py-2" onClick={() => move("verified", verifier)}>verified 전환</button><button className="rounded border bg-white px-3 py-2" onClick={makeCandidate}>Candidate 생성</button><button className="rounded border bg-white px-3 py-2" onClick={publish} disabled={!candidate}>publish</button><button className="rounded border bg-white px-3 py-2" onClick={rollback}>rollback</button></div>
  <section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Concept Checklist · Coverage</h2>{coverage.map((item) => <p key={item.conceptId} className="mt-1 text-sm">{item.conceptId} · {item.score}% · checklist {workflow.checklists.find(({ conceptId }) => conceptId === item.conceptId)?.completed ? "완료" : "대기"}</p>)}</section>
  <section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Release Candidate · Published</h2>{candidate && <p className="mt-2 text-sm">Candidate {candidate.releaseId} · checksum {candidate.checksum}</p>}{published.map((release) => <div key={release.releaseId} className="mt-2 flex items-center gap-2 text-sm"><span>{release.releaseId} · {release.status}</span><button className="rounded border px-2 py-1" onClick={() => activate(release.releaseId)}>Active 지정</button></div>)}</section>
  <section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Review Assignment</h2><p className="mt-2 text-sm">reviewer: {reviewer.actorId} · verifier: {verifier.actorId} · 역할 분리</p></section><section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Audit Log</h2>{audit.map((event) => <p key={event.eventId + event.createdAt} className="mt-1 text-xs">{event.action} · {event.previousStatus} → {event.nextStatus} · {event.actorRole}</p>)}</section>
  </div></main>;
}
