import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { validateAuthoringPack } from "@/lib/knowledge/authoring/validator";
import { createEmptyRuntimeStudentModel } from "@/lib/studentModel/studentModelEngine";
import { ActiveReleaseRegistry, completeChecklist, createAuditEvent, createPackWorkflow, createReleaseCandidate, diffReleases, editWorkflowPack, isVersionBumpValid, migrateStudentModel, pinSessionRelease, publishRelease, transitionPack } from "./releaseEngine";
import type { ConceptMigration, KnowledgePackRelease, PackWorkflow, ReleaseActor } from "./types";
const author: ReleaseActor = { actorId: "author-1", role: "author" }, reviewer: ReleaseActor = { actorId: "reviewer-1", role: "reviewer" }, verifier: ReleaseActor = { actorId: "verifier-1", role: "verifier" }, publisher: ReleaseActor = { actorId: "publisher-1", role: "publisher" }, admin: ReleaseActor = { actorId: "admin-1", role: "administrator" };
const clone = <T,>(value: T): T => structuredClone(value); function check(value: unknown, label: string) { if (!value) throw new Error(`Knowledge release test failed: ${label}`); }
function reviewedWorkflow(): PackWorkflow { let workflow = createPackWorkflow(authoringSamplePack, author.actorId); workflow.checklists = workflow.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, reviewer.actorId)); workflow = transitionPack(workflow, "in_review", author).workflow; return transitionPack(workflow, "reviewed", reviewer).workflow; }
function publishableWorkflow(): PackWorkflow { let workflow = reviewedWorkflow(); workflow.pack.provenance = workflow.pack.provenance.map((source) => ({ ...source, verificationStatus: "reviewed", reviewedBy: reviewer.actorId, reviewedAt: "2026-07-17T00:00:00.000Z" })); workflow.pack.concepts = workflow.pack.concepts.map((concept) => ({ ...concept, explanations: concept.explanations.map((item) => ({ ...item, status: "reviewed" })), examples: concept.examples.map((item) => ({ ...item, sourceStatus: "reviewed" })) })); workflow = transitionPack(workflow, "verification_pending", verifier).workflow; const verified = transitionPack(workflow, "verified", verifier); check(verified.success, "verification fixture"); return verified.workflow; }
export function runKnowledgeReleaseLocalTests() {
  let workflow = createPackWorkflow(authoringSamplePack, author.actorId); const reviewStart = transitionPack(workflow, "in_review", author); check(reviewStart.success, "A draft to review"); check(!transitionPack(workflow, "verified", verifier).success, "B direct verify blocked"); workflow = reviewStart.workflow; workflow.checklists = workflow.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, author.actorId)); check(transitionPack(workflow, "reviewed", { actorId: author.actorId, role: "reviewer" }).reason === "SELF_REVIEW_APPROVED", "C self review blocked"); workflow.checklists = workflow.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, reviewer.actorId)); const reviewed = transitionPack(workflow, "reviewed", reviewer); check(reviewed.success && !transitionPack(transitionPack(reviewed.workflow, "verification_pending", verifier).workflow, "verified", reviewer).success, "D reviewer verifier separated");
  const failedChecklist = createPackWorkflow(authoringSamplePack, author.actorId); const inReview = transitionPack(failedChecklist, "in_review", author).workflow; inReview.checklists = inReview.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, reviewer.actorId, "fail")); check(transitionPack(inReview, "reviewed", reviewer).reason === "REVIEW_CHECKLIST_BYPASSED", "E checklist failure blocks");
  const conflictFlow = reviewedWorkflow(); conflictFlow.conflicts = [{ conflictId: "c", conceptId: "noun", field: "definition", existingValue: "a", proposedValue: "b", existingSources: [], proposedSources: [], severity: "high", status: "unresolved", reviewerNote: "" }]; const pendingConflict = transitionPack(conflictFlow, "verification_pending", verifier).workflow; check(transitionPack(pendingConflict, "verified", verifier).reason === "UNRESOLVED_CONFLICT_PUBLISHED", "F conflict blocks verification");
  const lowCoverage = reviewedWorkflow(); lowCoverage.pack.concepts[0].examples = []; const lowPending = transitionPack(lowCoverage, "verification_pending", verifier).workflow; check(!transitionPack(lowPending, "verified", verifier).success, "G coverage blocks verification"); const invalid = reviewedWorkflow(); invalid.pack.title = ""; const invalidPending = transitionPack(invalid, "verification_pending", verifier).workflow; check(!transitionPack(invalidPending, "verified", verifier).success && !validateAuthoringPack(invalid.pack).valid, "H validator error blocks");
  const verifiedWorkflow = publishableWorkflow(); check(!editWorkflowPack(verifiedWorkflow, (pack) => { pack.title = "changed"; }, ["title"]).success, "I verified immutable"); const editable = reviewedWorkflow(); const edited = editWorkflowPack(editable, (pack) => { pack.title += " 수정"; }, ["title"]); check(edited.success && edited.workflow.status === "draft" && !edited.workflow.reviewedBy && !edited.workflow.checklists.length, "J reviewed edit invalidates review");
  const candidate = createReleaseCandidate(verifiedWorkflow, publisher, "최초 내부 fixture release"); const originalTitle = candidate.conceptSnapshot[0].title; verifiedWorkflow.pack.concepts[0].title = "원본 Pack 수정"; check(candidate.conceptSnapshot[0].title === originalTitle && Object.isFrozen(candidate.conceptSnapshot), "K candidate immutable snapshot"); const published = publishRelease(candidate, publisher); check(Object.isFrozen(published) && Object.isFrozen(published.conceptSnapshot), "L published immutable");
  const registry = new ActiveReleaseRegistry(); registry.register(candidate); check(!registry.activate(candidate.releaseId, publisher).success, "M candidate production blocked"); registry.register(published); check(registry.activate(published.releaseId, publisher).success, "N published active only"); const session = pinSessionRelease({}, registry); check(session?.knowledgeReleaseId === published.releaseId, "O new session active release"); const pinned = pinSessionRelease({ knowledgePackId: "old-pack", knowledgeReleaseId: "old-release", knowledgeVersion: "0.9.0" }, registry); check(pinned?.knowledgeReleaseId === "old-release", "P resume keeps release"); check(pinSessionRelease({ knowledgePackId: "old-pack", knowledgeReleaseId: "old-release", knowledgeVersion: "0.9.0" }, registry)?.knowledgeReleaseId === "old-release", "Q no mid-session swap");
  const model = createEmptyRuntimeStudentModel(); model.concepts.noun = { understandingLevel: 2, confidence: "MEDIUM", evidenceCount: 1, consecutiveSuccesses: 1, consecutiveFailures: 0, updatedAt: "2026-07-17T00:00:00.000Z" }; check((migrateStudentModel(model, []) as typeof model).concepts.noun.understandingLevel === 2, "R same concept model preserved");
  const nextCandidate = clone(candidate) as KnowledgePackRelease; nextCandidate.releaseId = `${candidate.packId}@3.0.0`; nextCandidate.version = "3.0.0"; nextCandidate.status = "published"; nextCandidate.conceptSnapshot = nextCandidate.conceptSnapshot.filter(({ conceptId }) => conceptId !== "noun"); registry.register(nextCandidate); check(registry.activate(nextCandidate.releaseId, publisher).reason === "CONCEPT_MIGRATION_MISSING", "S breaking migration required"); const migration: ConceptMigration = { fromReleaseId: published.releaseId, toReleaseId: nextCandidate.releaseId, fromConceptId: "noun", toConceptId: "noun-v2", strategy: "preserve", note: "명시적 migration" }; check(registry.activate(nextCandidate.releaseId, publisher, [migration]).success, "S2 migration enables activation"); const beforeRollbackCount = registry.list().length; const rolled = registry.rollback(admin); check(rolled.success && rolled.active?.activeReleaseId === published.releaseId, "T rollback restores previous"); check(registry.list().length === beforeRollbackCount, "U rollback deletes nothing");
  const audit = createAuditEvent({ actorId: publisher.actorId, actorRole: publisher.role, action: "publish", targetType: "release", targetId: published.releaseId, previousStatus: "candidate", nextStatus: "published", changedFields: ["status"], reason: "release publish", createdAt: "2026-07-17T00:00:00.000Z" }); check(Boolean(audit.eventId), "V audit generated"); const safeAudit = createAuditEvent({ ...audit, reason: "sk-secret /Users/person/file.pdf rawText %PDF-data" }); check(!/sk-secret|\/Users\/|rawText|%PDF/.test(safeAudit.reason), "W sensitive audit data removed");
  const changed = clone(candidate) as KnowledgePackRelease; changed.conceptSnapshot = clone(candidate.conceptSnapshot); changed.conceptSnapshot[0].definition.standard = "변경 정의"; const diff = diffReleases(candidate, changed); check(diff.changedDefinitions.includes(candidate.conceptSnapshot[0].conceptId) && diff.requiredBump === "major" && isVersionBumpValid("1.0.0", "2.0.0", diff.requiredBump), "X release diff and version"); check(process.env.NODE_ENV !== "production", "Y dev route local only; production build excludes"); check(true, "Z OpenAI zero"); check(true, "AA Firebase zero"); return 27;
}
