import { calculateConceptCoverage } from "@/lib/knowledge/authoring/coverage";
import { validateAuthoringPack } from "@/lib/knowledge/authoring/validator";
import type { AuthoringKnowledgePack, PackStatus } from "@/lib/knowledge/authoring/types";
import type { StudentSessionModel } from "@/lib/types/chat";
import type { ActiveKnowledgeRelease, ConceptMigration, ConceptReviewChecklist, KnowledgeAuditEvent, KnowledgePackRelease, PackWorkflow, ReleaseActor, ReleaseDiff } from "./types";

export const REVIEW_CHECKLIST_KEYS = ["curriculum_scope", "definition_consistency", "core_understanding", "applicable_rules", "concept_relations", "example_accuracy", "counterexample_accuracy", "misconception_correction", "check_answer_alignment", "worked_example_steps", "measurable_completion", "provenance_sufficient", "copyright_safe", "internal_id_hidden"] as const;
const transitions: Record<PackStatus, PackStatus[]> = { draft: ["in_review", "rejected"], in_review: ["reviewed", "rejected"], reviewed: ["verification_pending", "draft", "in_review"], verification_pending: ["verified", "draft", "in_review"], verified: ["published"], published: ["archived"], archived: [], rejected: [] };
const permissions: Record<string, string[]> = { "draft:in_review": ["author", "administrator"], "draft:rejected": ["reviewer", "administrator"], "in_review:reviewed": ["reviewer"], "in_review:rejected": ["reviewer", "administrator"], "reviewed:verification_pending": ["reviewer", "verifier"], "reviewed:draft": ["author"], "reviewed:in_review": ["author"], "verification_pending:verified": ["verifier"], "verification_pending:draft": ["author"], "verification_pending:in_review": ["author"], "verified:published": ["publisher"], "published:archived": ["publisher", "administrator"] };
const clone = <T,>(value: T): T => structuredClone(value);
export function createPackWorkflow(pack: AuthoringKnowledgePack, authoredBy: string): PackWorkflow { return { pack: clone(pack), status: pack.status, authoredBy, reviewedBy: null, reviewedAt: null, verifiedBy: null, verifiedAt: null, checklists: [], conflicts: [], modifiedFields: [] }; }
export function isChecklistComplete(checklist: ConceptReviewChecklist) { return checklist.entries.length >= REVIEW_CHECKLIST_KEYS.length && REVIEW_CHECKLIST_KEYS.every((key) => checklist.entries.some((entry) => entry.key === key && (entry.decision === "pass" || entry.decision === "not_applicable"))); }
export function completeChecklist(conceptId: string, reviewerId: string, decision: "pass" | "fail" | "needs_revision" = "pass", now = new Date().toISOString()): ConceptReviewChecklist { const entries = REVIEW_CHECKLIST_KEYS.map((key) => ({ key, decision, note: "", reviewerId, reviewedAt: now })); return { conceptId, entries, completed: decision === "pass" }; }
function verificationGate(workflow: PackWorkflow) { const validation = validateAuthoringPack(workflow.pack); const blockingWarnings = validation.issues.filter(({ severity, code }) => severity === "warning" && code !== "KNOWLEDGE_COVERAGE_INSUFFICIENT"); const coverageComplete = workflow.pack.concepts.every((concept) => calculateConceptCoverage(concept).score === 100); const reviewsComplete = workflow.pack.concepts.every((concept) => workflow.checklists.some((item) => item.conceptId === concept.conceptId && isChecklistComplete(item))); const provenanceValid = workflow.pack.provenance.every(({ verificationStatus, reviewedBy, reviewedAt }) => verificationStatus !== "draft" && Boolean(reviewedBy && reviewedAt)); const mixedDraft = workflow.pack.concepts.some((concept) => concept.explanations.some(({ status }) => status === "draft") || concept.examples.some(({ sourceStatus }) => sourceStatus === "draft")); return { valid: validation.valid && blockingWarnings.length === 0 && coverageComplete && reviewsComplete && !workflow.conflicts.some(({ status }) => status === "unresolved") && provenanceValid && !mixedDraft, validation, coverageComplete, reviewsComplete, provenanceValid, mixedDraft }; }
export function transitionPack(workflow: PackWorkflow, nextStatus: PackStatus, actor: ReleaseActor, now = new Date().toISOString()) {
  if (!transitions[workflow.status].includes(nextStatus)) return { success: false, reason: "INVALID_PACK_STATUS_TRANSITION", workflow };
  if (!(permissions[`${workflow.status}:${nextStatus}`] ?? []).includes(actor.role)) return { success: false, reason: "ROLE_NOT_ALLOWED", workflow };
  if (nextStatus === "reviewed") { if (actor.actorId === workflow.authoredBy) return { success: false, reason: "SELF_REVIEW_APPROVED", workflow }; if (!workflow.pack.concepts.every((concept) => workflow.checklists.some((item) => item.conceptId === concept.conceptId && isChecklistComplete(item)))) return { success: false, reason: "REVIEW_CHECKLIST_BYPASSED", workflow }; }
  if (nextStatus === "verified") { if (actor.actorId === workflow.authoredBy || actor.actorId === workflow.reviewedBy) return { success: false, reason: "REVIEWER_VERIFIER_NOT_SEPARATED", workflow }; const gate = verificationGate(workflow); if (!gate.valid) return { success: false, reason: !gate.coverageComplete ? "INCOMPLETE_COVERAGE_VERIFIED" : workflow.conflicts.some(({ status }) => status === "unresolved") ? "UNRESOLVED_CONFLICT_PUBLISHED" : "VERIFICATION_GATE_FAILED", workflow }; }
  const updated = clone(workflow); updated.status = nextStatus; updated.pack.status = nextStatus;
  if (nextStatus === "reviewed") { updated.reviewedBy = actor.actorId; updated.reviewedAt = now; }
  if (nextStatus === "verified") { updated.verifiedBy = actor.actorId; updated.verifiedAt = now; }
  return { success: true, reason: "", workflow: updated };
}
export function editWorkflowPack(workflow: PackWorkflow, mutate: (pack: AuthoringKnowledgePack) => void, changedFields: string[]) { if (["verified", "published", "archived"].includes(workflow.status)) return { success: false, reason: "VERIFIED_CONTENT_IMMUTABLE", workflow }; const updated = clone(workflow); mutate(updated.pack); updated.status = workflow.status === "reviewed" || workflow.status === "verification_pending" ? "draft" : workflow.status; updated.pack.status = updated.status; updated.reviewedBy = null; updated.reviewedAt = null; updated.verifiedBy = null; updated.verifiedAt = null; updated.checklists = []; updated.modifiedFields = [...new Set([...updated.modifiedFields, ...changedFields])]; return { success: true, reason: "", workflow: updated }; }
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stable(item)}`).join(",")}}`; return JSON.stringify(value); }
function checksum(value: unknown) { const text = stable(value); let hash = 2166136261; for (let index = 0; index < text.length; index += 1) hash = Math.imul(hash ^ text.charCodeAt(index), 16777619); return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value as object).forEach(deepFreeze); } return value; }
export function createReleaseCandidate(workflow: PackWorkflow, actor: ReleaseActor, releaseNotes: string, previous?: KnowledgePackRelease, now = new Date().toISOString()): KnowledgePackRelease {
  if (workflow.status !== "verified" || actor.role !== "publisher" || !releaseNotes.trim()) throw new Error("UNVERIFIED_PACK_RELEASED");
  const validation = validateAuthoringPack(workflow.pack);
  const retrievalSmokePassed = workflow.pack.concepts.every((concept) => concept.definition.standard.trim() && concept.examples.length > 0);
  const conversationSmokePassed = workflow.pack.concepts.every((concept) => concept.checks.some((check) => check.prompt.trim() && check.correctAnswer.trim()));
  if (!validation.valid || !retrievalSmokePassed || !conversationSmokePassed) throw new Error("RELEASE_CANDIDATE_SMOKE_TEST_FAILED");
  const conceptSnapshot = deepFreeze(clone(workflow.pack.concepts)), provenanceSnapshot = deepFreeze(clone(workflow.pack.provenance));
  if (previous) {
    const next = { conceptSnapshot, provenanceSnapshot };
    const requiredBump = diffReleases(previous, next).requiredBump;
    if (!isVersionBumpValid(previous.version, workflow.pack.version, requiredBump)) throw new Error("INVALID_VERSION_BUMP");
  }
  return deepFreeze({ releaseId: `${workflow.pack.packId}@${workflow.pack.version}`, packId: workflow.pack.packId, version: workflow.pack.version, schemaVersion: workflow.pack.schemaVersion, status: "candidate", conceptSnapshot, provenanceSnapshot, checksum: checksum({ conceptSnapshot, provenanceSnapshot }), releaseNotes: releaseNotes.trim(), createdBy: actor.actorId, verifiedBy: workflow.verifiedBy!, publishedBy: null, createdAt: now, verifiedAt: workflow.verifiedAt!, publishedAt: null, supersedesReleaseId: previous?.releaseId ?? null, rollbackTargetIds: previous ? [previous.releaseId, ...previous.rollbackTargetIds] : [] } as KnowledgePackRelease);
}
export function publishRelease(candidate: KnowledgePackRelease, actor: ReleaseActor, now = new Date().toISOString()) { if (candidate.status !== "candidate" || actor.role !== "publisher") throw new Error("UNVERIFIED_PACK_RELEASED"); return deepFreeze({ ...clone(candidate), status: "published" as const, publishedBy: actor.actorId, publishedAt: now }); }
export function diffReleases(left: Pick<KnowledgePackRelease, "conceptSnapshot" | "provenanceSnapshot">, right: Pick<KnowledgePackRelease, "conceptSnapshot" | "provenanceSnapshot">): ReleaseDiff { const a = new Map(left.conceptSnapshot.map((item) => [item.conceptId, item])), b = new Map(right.conceptSnapshot.map((item) => [item.conceptId, item])); const shared = [...a.keys()].filter((id) => b.has(id)); const changed = <T,>(select: (value: NonNullable<ReturnType<typeof a.get>>) => T) => shared.filter((id) => stable(select(a.get(id)!)) !== stable(select(b.get(id)!))); const addedConcepts = [...b.keys()].filter((id) => !a.has(id)), deletedConcepts = [...a.keys()].filter((id) => !b.has(id)); const changedDefinitions = changed((item) => item.definition), changedDiscriminationRules = changed((item) => item.discriminationRules), changedPrerequisites = changed((item) => item.prerequisites), changedCompletionCriteria = changed((item) => item.completionCriteria); const exampleIds = (map: typeof a) => new Set([...map.values()].flatMap((item) => item.examples.map(({ exampleId }) => exampleId))); const ae = exampleIds(a), be = exampleIds(b); const major = Boolean(addedConcepts.length || deletedConcepts.length || changedDefinitions.length || changedDiscriminationRules.length || changedPrerequisites.length || changedCompletionCriteria.length); return { addedConcepts, deletedConcepts, changedDefinitions, changedDiscriminationRules, changedPrerequisites, changedCompletionCriteria, addedExamples: [...be].filter((id) => !ae.has(id)), deletedExamples: [...ae].filter((id) => !be.has(id)), changedAnswers: changed((item) => item.checks.map(({ checkId, correctAnswer }) => [checkId, correctAnswer])), changedMisconceptions: changed((item) => item.misconceptions), changedProvenance: stable(left.provenanceSnapshot) !== stable(right.provenanceSnapshot), requiredBump: major ? "major" : [...be].some((id) => !ae.has(id)) ? "minor" : "patch" }; }
export function isVersionBumpValid(previous: string, next: string, required: ReleaseDiff["requiredBump"]) { const semver = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/; const aMatch = previous.match(semver), bMatch = next.match(semver); if (!aMatch || !bMatch) return false; const a = aMatch.slice(1).map(Number), b = bMatch.slice(1).map(Number); return required === "major" ? b[0] > a[0] : required === "minor" ? b[0] > a[0] || (b[0] === a[0] && b[1] > a[1]) : b[0] > a[0] || b[1] > a[1] || b[2] > a[2]; }
export class ActiveReleaseRegistry { private releases = new Map<string, KnowledgePackRelease>(); private active: ActiveKnowledgeRelease | null = null; register(release: KnowledgePackRelease) { this.releases.set(release.releaseId, release); } activate(releaseId: string, actor: ReleaseActor, migrations: ConceptMigration[] = [], now = new Date().toISOString()) { const release = this.releases.get(releaseId); if (!release || release.status !== "published") return { success: false, reason: "UNPUBLISHED_RELEASE_USED" }; const previous = this.active ? this.releases.get(this.active.activeReleaseId) : undefined; if (previous) { const diff = diffReleases(previous, release); const removed = [...diff.deletedConcepts, ...diff.changedPrerequisites]; if (removed.length && !removed.every((id) => migrations.some(({ fromConceptId }) => fromConceptId === id))) return { success: false, reason: "CONCEPT_MIGRATION_MISSING" }; } this.active = { subject: "국어", domain: "문법", schoolLevel: "middle", gradeRange: [1, 2, 3], activeReleaseId: releaseId, previousReleaseId: this.active?.activeReleaseId ?? null, activatedAt: now, activatedBy: actor.actorId }; return { success: true, reason: "", active: clone(this.active) }; } getActive() { return this.active ? clone(this.active) : null; } getRelease(id: string) { return this.releases.get(id) ?? null; } rollback(actor: ReleaseActor, now = new Date().toISOString()) { if (!this.active?.previousReleaseId || actor.role !== "administrator") return { success: false, reason: "ROLLBACK_UNAVAILABLE" }; const target = this.releases.get(this.active.previousReleaseId); if (!target || target.status !== "published") return { success: false, reason: "ROLLBACK_UNAVAILABLE" }; const current = this.active.activeReleaseId; this.active = { ...this.active, activeReleaseId: target.releaseId, previousReleaseId: current, activatedAt: now, activatedBy: actor.actorId }; return { success: true, active: clone(this.active) }; } list() { return [...this.releases.values()]; } }
export function pinSessionRelease(model: Partial<StudentSessionModel>, registry: ActiveReleaseRegistry) { if (model.knowledgeReleaseId) return { knowledgePackId: model.knowledgePackId!, knowledgeReleaseId: model.knowledgeReleaseId, knowledgeVersion: model.knowledgeVersion! }; const active = registry.getActive(); if (!active) return null; const release = registry.getRelease(active.activeReleaseId); return release ? { knowledgePackId: release.packId, knowledgeReleaseId: release.releaseId, knowledgeVersion: release.version } : null; }
const sensitive = /(?:sk-[A-Za-z0-9_-]+)|(?:\/Users\/|[A-Za-z]:\\)|(?:%PDF-|rawText)/gi;
export function createAuditEvent(input: Omit<KnowledgeAuditEvent, "eventId" | "createdAt" | "reason"> & { reason: string; createdAt?: string }): KnowledgeAuditEvent { return { ...input, eventId: `audit-${Math.abs(input.targetId.split("").reduce((sum, char) => sum * 31 + char.charCodeAt(0), 7))}`, reason: input.reason.replace(sensitive, "[REDACTED]").slice(0, 500), createdAt: input.createdAt ?? new Date().toISOString() }; }
export function migrateStudentModel<T>(model: T, migrations: ConceptMigration[]) { if (!model || typeof model !== "object") return model; const value = clone(model) as Record<string, unknown>; if (value.concepts && typeof value.concepts === "object") { const concepts = value.concepts as Record<string, unknown>; for (const migration of migrations) if (migration.strategy === "preserve" && concepts[migration.fromConceptId] && migration.fromConceptId !== migration.toConceptId) { concepts[migration.toConceptId] = concepts[migration.fromConceptId]; delete concepts[migration.fromConceptId]; } } return value as T; }
