"use client";
import { useMemo, useState } from "react";
import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { FixtureDocumentExtractor } from "@/lib/knowledge/ingestion/extractors";
import { ingestSourceDocument } from "@/lib/knowledge/ingestion/pipeline";
import { applyReviewedItemsToDraft, createReviewItems, decideReviewItem } from "@/lib/knowledge/ingestion/review";
import { LocalSourceStorage } from "@/lib/knowledge/ingestion/storage";
import type { ExtractionBundle, ReviewDecision, ReviewItem } from "@/lib/knowledge/ingestion/types";
const storage = new LocalSourceStorage();
const metadata = { documentId: "dev-fixture-document", sourceId: "dev-fixture-source", title: "한잎 자체 제작 문법 테스트 문서", sourceType: "internalOriginal" as const, curriculumYear: "2022", gradeRange: [1, 2, 3] };
export default function SourcesClient() {
  const [bundle, setBundle] = useState<ExtractionBundle | null>(null), [reviews, setReviews] = useState<ReviewItem[]>([]), [type, setType] = useState("all"), [warningOnly, setWarningOnly] = useState(false), [minimumConfidence, setMinimumConfidence] = useState(0), [conflicts, setConflicts] = useState<string[]>([]), [notice, setNotice] = useState("");
  const chunks = useMemo(() => (bundle?.chunks ?? []).filter((chunk) => (type === "all" || chunk.candidateTypes.includes(type as never)) && chunk.confidence >= minimumConfidence && (!warningOnly || bundle?.pages.find(({ pageNumber }) => String(pageNumber) === chunk.pageRange)?.warnings.length)), [bundle, minimumConfidence, type, warningOnly]);
  async function start() { const bytes = new TextEncoder().encode("%PDF-1.7\n한잎 문법\n1\n품사란 단어를 문법적 성질에 따라 나눈 갈래이다.\n예를 들어 사람과 예쁘다를 비교한다.\n한잎 개발\f한잎 문법\n2\n확인 문제: 품사를 어떤 기준으로 나눌까?\n한잎 개발\n%%EOF"); const result = await ingestSourceDocument({ file: { fileName: "hanip-test.fixture.pdf", mimeType: "application/pdf", bytes }, metadata, extractor: new FixtureDocumentExtractor(), storage }); setBundle(result); setReviews(createReviewItems(result.document, result.chunks, ["parts-of-speech"])); setNotice("추출과 후보 분류를 완료했습니다."); }
  function decide(id: string, decision: Exclude<ReviewDecision, "pending">) { setReviews((items) => items.map((item) => item.reviewItemId === id ? decideReviewItem(item, decision, "개발 화면 검토") : item)); }
  function apply() { if (!bundle) return; const result = applyReviewedItemsToDraft(authoringSamplePack, reviews, bundle.document); setConflicts(result.conflicts.map(({ conflictId }) => conflictId)); setNotice(`${result.appliedReviewItemIds.length}개 항목을 draft에 반영했습니다.`); }
  return <main className="min-h-screen bg-zinc-100 px-4 py-8 text-black"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-zinc-600">Development only</p><h1 className="mt-1 text-3xl font-bold">Source Document Ingestion</h1><p className="mt-2 text-sm">자체 제작 fixture만 사용하며 원본 경로나 전체 텍스트를 로그에 남기지 않습니다.</p><div className="mt-5 flex gap-2"><button className="rounded-lg bg-black px-4 py-2 text-white" onClick={() => void start()}>테스트 문서 import·추출 시작</button><button className="rounded-lg border bg-white px-4 py-2" onClick={apply} disabled={!bundle}>검토 항목을 Pack draft에 반영</button></div>{notice && <p role="status" className="mt-3 text-sm">{notice}</p>}
  {bundle && <><section className="mt-5 grid gap-3 rounded-xl bg-white p-4 text-sm md:grid-cols-4"><p>문서 {bundle.document.title}</p><p>추출 {bundle.document.extractionStatus}</p><p>페이지 {bundle.pages.length}</p><p>Chunk {bundle.chunks.length}</p></section><section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">페이지별 원문·정규화 비교</h2>{bundle.pages.map((page) => <details key={page.pageNumber} className="mt-2"><summary>{page.pageNumber}쪽 · confidence {page.extractionConfidence} · {page.warnings.join(", ") || "warning 없음"}</summary><div className="mt-2 grid gap-2 md:grid-cols-2"><pre className="whitespace-pre-wrap rounded bg-zinc-100 p-2 text-xs">{page.rawText}</pre><pre className="whitespace-pre-wrap rounded bg-zinc-100 p-2 text-xs">{page.normalizedText}</pre></div></details>)}</section>
  <div className="mt-5 flex flex-wrap gap-2"><select value={type} onChange={(event) => setType(event.target.value)} className="rounded border bg-white px-3"><option value="all">모든 Chunk 유형</option><option value="definition_candidate">정의</option><option value="example_candidate">예문</option><option value="check_question_candidate">확인 문제</option></select><select value={minimumConfidence} onChange={(event) => setMinimumConfidence(Number(event.target.value))} className="rounded border bg-white px-3"><option value="0">모든 confidence</option><option value="0.8">0.8 이상</option></select><label className="flex items-center gap-2 rounded bg-white px-3"><input type="checkbox" checked={warningOnly} onChange={(event) => setWarningOnly(event.target.checked)}/> warning만</label></div>
  <section className="mt-5 grid gap-3">{chunks.map((chunk) => <article key={chunk.chunkId} className="rounded-xl bg-white p-4"><p className="font-bold">{chunk.heading || chunk.chunkId} · {chunk.pageRange}쪽</p><p className="mt-1 text-xs">{chunk.candidateTypes.join(", ")} · confidence {chunk.confidence}</p><p className="mt-2 text-sm">{chunk.normalizedText}</p></article>)}</section><section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Review Queue</h2>{reviews.map((item) => <article key={item.reviewItemId} className="mt-3 border-t pt-3"><textarea className="w-full rounded border p-2 text-sm" value={item.proposedContent} onChange={(event) => setReviews((items) => items.map((value) => value.reviewItemId === item.reviewItemId ? { ...value, proposedContent: event.target.value } : value))}/><div className="mt-2 flex flex-wrap gap-2">{(["accepted", "edited", "rejected", "deferred"] as const).map((decision) => <button key={decision} className="rounded border px-3 py-1 text-sm" onClick={() => decide(item.reviewItemId, decision)}>{decision}</button>)}<span className="text-sm">현재: {item.status}</span></div></article>)}</section><section className="mt-5 rounded-xl bg-white p-4"><h2 className="font-bold">Conflict</h2><p className="text-sm">{conflicts.length ? conflicts.join(", ") : "없음"}</p></section><details className="mt-5 rounded-xl bg-white p-4"><summary className="font-bold">추출 결과 JSON</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(bundle, null, 2)}</pre></details></>}
  </div></main>;
}
