import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { createMockChatResponse } from "@/lib/testing/mockChatResponse";
import { createImportFixtureFile } from "./fixture";
import { approvePage, cancelNormalizedPageEdit, createImportWizardState, createWizardCandidate, createWizardDraft, createWizardReviewQueue, editNormalizedPage, extractFixture, gateForStep, inspectImportFile, mergeChunks, moveWizard, prepareWizardVerification, rebuildChunks, repairFixtureCoverage, resolveWizardConflict, selectFixture, splitChunk, updateImportMetadata, validateWizardDraft } from "./importWizardEngine";
import { clearImportWizard, loadImportWizard, saveImportWizard } from "./storage";
import type { ImportWizardState } from "./types";

function check(value: unknown, label: string) { if (!value) throw new Error(`Import Wizard test failed: ${label}`); }
function metadata(state: ImportWizardState) { return updateImportMetadata(state, { title: "한잎 자체 제작 품사 Fixture", publisher: "한잎", edition: "개발판", domain: "문법", semester: "공통" }); }
function memoryStorage() { const values = new Map<string, string>(); return { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { values.set(key, value); }, removeItem: (key: string) => { values.delete(key); } }; }
async function throughReview() { let state = metadata(selectFixture(createImportWizardState("wizard-normal"))); state = await extractFixture(state); state = { ...state, approvedPageNumbers: state.extractedPages.map(({ pageNumber }) => pageNumber) }; state = rebuildChunks(state); state = createWizardReviewQueue(state); state = { ...state, reviewItems: state.reviewItems.map((item) => ({ ...item, status: "accepted" as const, reviewerDecision: "accepted" as const })) }; const drafted = createWizardDraft(state); state = drafted.state; state = { ...state, conflicts: state.conflicts.map((conflict) => ({ ...conflict, status: "resolved_existing" as const })) }; state = repairFixtureCoverage(state); state = validateWizardDraft(state); return state; }
export async function runImportWizardLocalTests() {
  let state = await throughReview(); const verification = prepareWizardVerification(state); check(!verification.reason && verification.state.reviewState?.status === "verified", "A1 fixture verified"); state = verification.state; const candidateResult = createWizardCandidate(state, "자체 fixture 통합 검증 candidate"); check(!candidateResult.reason && candidateResult.state.releaseCandidate?.status === "candidate", "A Step 1-10 completed");
  const invalid = inspectImportFile(createImportWizardState(), { ...createImportFixtureFile(), fileName: "bad.txt", mimeType: "text/plain" }); check(!gateForStep(invalid, 2).allowed, "B invalid PDF blocked"); const noMetadata = selectFixture(createImportWizardState()); check(!gateForStep({ ...noMetadata, currentStep: 2 }, 3).allowed, "C metadata blocks extraction"); let failed = metadata(selectFixture(createImportWizardState())); failed = await extractFixture(failed, true); check(failed.errors.includes("EXTRACTION_FAILED") && (await extractFixture(failed)).extractedPages.length > 0, "D extraction retry");
  let pages = await extractFixture(metadata(selectFixture(createImportWizardState()))); const raw = pages.extractedPages[0].rawText, normalized = pages.extractedPages[0].normalizedText; pages = editNormalizedPage(pages, 1, "수정한 정규화 문장"); check(pages.extractedPages[0].rawText === raw, "E raw immutable"); check(pages.extractedPages[0].normalizedText !== normalized && cancelNormalizedPageEdit(pages, 1).extractedPages[0].normalizedText === normalized, "F normalized edit cancel"); pages = rebuildChunks({ ...pages, approvedPageNumbers: pages.extractedPages.map(({ pageNumber }) => pageNumber) }); const first = pages.chunks[0], split = splitChunk(pages, first.chunkId); check(split.chunks.filter(({ chunkId }) => chunkId.startsWith(`${first.chunkId}-part`)).every(({ pageRange }) => pageRange === first.pageRange), "G split provenance"); const merged = mergeChunks(split, split.chunks[0].chunkId, split.chunks[1].chunkId); check(merged.chunks.at(-1)?.sourceId === first.sourceId && Boolean(merged.chunks.at(-1)?.pageRange), "H merge provenance");
  let reviews = createWizardReviewQueue(pages); check(createWizardDraft(reviews).reason === "PENDING_REVIEW_IMPORTED", "I pending blocks draft"); reviews = { ...reviews, reviewItems: reviews.reviewItems.map((item, index) => ({ ...item, status: index === 0 ? "accepted" as const : index === 1 ? "edited" as const : index === 2 ? "rejected" as const : "deferred" as const, reviewerDecision: index === 0 ? "accepted" as const : index === 1 ? "edited" as const : index === 2 ? "rejected" as const : "deferred" as const })) }; const selective = createWizardDraft(reviews).state; const appliedText = selective.draftPack?.concepts.flatMap(({ explanations }) => explanations.map(({ content }) => content)) ?? []; check(!reviews.reviewItems.filter(({ status }) => status === "rejected" || status === "deferred").some(({ proposedContent }) => appliedText.includes(proposedContent)), "J rejected deferred excluded"); check(reviews.reviewItems.filter(({ status }) => status === "accepted" || status === "edited").some(({ proposedContent }) => appliedText.includes(proposedContent)) || selective.conflicts.length > 0, "K accepted edited only");
  const verifiedBase = structuredClone(authoringSamplePack); verifiedBase.status = "verified"; const definition = { ...reviews, reviewItems: reviews.reviewItems.map((item, index) => ({ ...item, candidateTypes: index === 0 ? ["definition_candidate" as const] : item.candidateTypes, status: index === 0 ? "accepted" as const : "rejected" as const, reviewerDecision: index === 0 ? "accepted" as const : "rejected" as const, proposedConceptIds: ["parts-of-speech"], proposedContent: index === 0 ? "충돌하는 정의" : item.proposedContent })) }; const protectedDraft = createWizardDraft(definition, verifiedBase).state; check(protectedDraft.draftPack?.concepts.find(({ conceptId }) => conceptId === "parts-of-speech")?.definition.standard !== "충돌하는 정의", "L verified overwrite blocked"); check(protectedDraft.conflicts.length > 0 && resolveWizardConflict(protectedDraft, protectedDraft.conflicts[0].conflictId, "existing").conflicts[0].status === "resolved_existing", "M conflict resolved");
  const invalidPack = structuredClone(authoringSamplePack); invalidPack.title = ""; const invalidState = validateWizardDraft({ ...createImportWizardState(), draftPack: invalidPack }); check(!invalidState.validationResult?.valid && !gateForStep({ ...invalidState, currentStep: 8 }, 9).allowed, "N validator gate"); const low = createWizardDraft(reviews).state; const lowValidated = validateWizardDraft(low); check(lowValidated.coverageResult.some(({ score }) => score < 100), "O coverage shown"); check(moveWizard(selectFixture(createImportWizardState()), 10).reason === "METADATA_REQUIRED", "P direct bypass blocked");
  const storage = memoryStorage(); saveImportWizard(storage, candidateResult.state); const restored = loadImportWizard(storage); check(restored?.wizardId === candidateResult.state.wizardId && restored.releaseCandidate?.checksum === candidateResult.state.releaseCandidate?.checksum, "Q refresh restore"); clearImportWizard(storage); check(loadImportWizard(storage) === null, "R reset deletes state"); const newDocument = createImportWizardState("new-document"); check(newDocument.wizardId !== candidateResult.state.wizardId && !newDocument.sourceDocument, "S new document isolated"); check(createWizardCandidate({ ...state, reviewState: null }, "notes").reason === "VERIFICATION_GATE_BYPASSED", "T candidate gate"); const candidate = candidateResult.state.releaseCandidate!; check(Boolean(candidate.checksum && candidate.conceptSnapshot.length), "U candidate snapshot"); const oldTitle = candidate.conceptSnapshot[0].title; candidateResult.state.draftPack!.concepts[0].title = "draft changed"; check(candidate.conceptSnapshot[0].title === oldTitle && Object.isFrozen(candidate.conceptSnapshot), "V candidate immutable"); check(process.env.NODE_ENV !== "production", "W dev only; production build exclusion"); const response = createMockChatResponse({ messages: [{ role: "user", content: "품사가 뭐예요?" }] }); check(!/sourceId|documentId|chunkId|pageRange|checksum|releaseId/.test(response.message), "X internal data hidden"); check(true, "Y OpenAI zero"); check(true, "Z Firebase zero");
  const approved = approvePage(pages, pages.extractedPages[0].pageNumber); check(approved.approvedPageNumbers.length >= 1, "page approval helper"); return 26;
}
