import { calculateConceptCoverage } from "@/lib/knowledge/authoring/coverage";
import { authoringSamplePack } from "@/lib/knowledge/authoring/samplePack";
import { validateAuthoringPack } from "@/lib/knowledge/authoring/validator";
import { FixtureDocumentExtractor } from "@/lib/knowledge/ingestion/extractors";
import { validateSourceFile } from "@/lib/knowledge/ingestion/fileValidation";
import { ingestSourceDocument } from "@/lib/knowledge/ingestion/pipeline";
import { applyReviewedItemsToDraft, createReviewItems, decideReviewItem } from "@/lib/knowledge/ingestion/review";
import { LocalSourceStorage } from "@/lib/knowledge/ingestion/storage";
import type { CandidateType, ContentConflict, IngestionSourceChunk, ReviewDecision, SourceFileInput } from "@/lib/knowledge/ingestion/types";
import { completeChecklist, createPackWorkflow, createReleaseCandidate, transitionPack } from "@/lib/knowledge/release/releaseEngine";
import type { ReleaseActor } from "@/lib/knowledge/release/types";
import { createImportFixtureFile } from "./fixture";
import type { ImportDocumentMetadata, ImportWizardState, ImportWizardStep, WizardGateResult } from "./types";

const NOW = "2026-07-17T00:00:00.000Z";
export const IMPORT_REVIEWER: ReleaseActor = { actorId: "import-reviewer", role: "reviewer" };
export const IMPORT_VERIFIER: ReleaseActor = { actorId: "import-verifier", role: "verifier" };
export const IMPORT_PUBLISHER: ReleaseActor = { actorId: "import-publisher", role: "publisher" };
export const IMPORT_AUTHOR: ReleaseActor = { actorId: "import-author", role: "author" };
const emptyMetadata: ImportDocumentMetadata = { title: "", sourceType: "internalOriginal", publisher: "", edition: "", curriculumYear: "2022", schoolLevel: "middle", gradeRange: [1, 2, 3], subject: "국어", domain: "문법", semester: "공통", note: "" };
const touch = (state: ImportWizardState): ImportWizardState => ({ ...state, dirty: true, updatedAt: new Date().toISOString() });
function checksum(bytes: Uint8Array) { let hash = 2166136261; for (const byte of bytes) hash = Math.imul(hash ^ byte, 16777619); return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
export function createImportWizardState(id = `import-${Date.now()}`): ImportWizardState { return { wizardId: id, currentStep: 1, fileInspection: null, metadata: { ...emptyMetadata }, sourceDocument: null, extractedPages: [], approvedPageNumbers: [], originalNormalizedText: {}, chunks: [], reviewItems: [], conflicts: [], draftPack: null, validationResult: null, coverageResult: [], reviewState: null, releaseCandidate: null, releaseNotes: "", dirty: false, lastSavedAt: null, createdAt: NOW, updatedAt: NOW, errors: [] }; }
export function inspectImportFile(state: ImportWizardState, file: SourceFileInput): ImportWizardState { const validation = validateSourceFile(file), inspection = new FixtureDocumentExtractor().inspect(file); return touch({ ...state, fileInspection: { fileName: validation.safeFileName, mimeType: file.mimeType, fileSize: file.bytes.byteLength, pageCount: inspection.pageCount, checksum: checksum(file.bytes), encrypted: inspection.encrypted, extractable: validation.valid && inspection.valid, warnings: inspection.warnings, errors: [...validation.errors, ...(inspection.valid ? [] : inspection.warnings)] }, errors: validation.errors }); }
export function selectFixture(state: ImportWizardState) { return inspectImportFile(state, createImportFixtureFile()); }
export function updateImportMetadata(state: ImportWizardState, metadata: Partial<ImportDocumentMetadata>) { return touch({ ...state, metadata: { ...state.metadata, ...metadata } }); }
function metadataComplete(metadata: ImportDocumentMetadata) { return Boolean(metadata.title.trim() && metadata.curriculumYear.trim() && metadata.schoolLevel && metadata.gradeRange.length && metadata.subject && metadata.domain.trim() && metadata.semester.trim()); }
export function gateForStep(state: ImportWizardState, target: ImportWizardStep): WizardGateResult {
  if (target <= state.currentStep) return { allowed: true, reason: "" };
  for (let step = state.currentStep; step < target; step += 1) {
    if (step === 1 && (!state.fileInspection?.extractable || state.fileInspection.errors.length)) return { allowed: false, reason: "FILE_VALIDATION_FAILED" };
    if (step === 2 && !metadataComplete(state.metadata)) return { allowed: false, reason: "METADATA_REQUIRED" };
    if (step === 3 && (!state.sourceDocument || state.sourceDocument.extractionStatus === "failed" || !state.extractedPages.length)) return { allowed: false, reason: "EXTRACTION_REQUIRED" };
    if (step === 4 && state.approvedPageNumbers.length !== state.extractedPages.length) return { allowed: false, reason: "PAGE_APPROVAL_REQUIRED" };
    if (step === 5 && state.chunks.some(({ status }) => status !== "reviewed" && status !== "rejected")) return { allowed: false, reason: "CHUNK_REVIEW_REQUIRED" };
    if (step === 6 && state.reviewItems.some(({ status }) => status === "pending")) return { allowed: false, reason: "PENDING_REVIEW_IMPORTED" };
    if (step === 7 && (!state.draftPack || state.conflicts.some(({ status }) => status === "unresolved"))) return { allowed: false, reason: "UNRESOLVED_CONFLICT" };
    if (step === 8 && (!state.validationResult?.valid || state.validationResult.issues.some(({ severity }) => severity === "error"))) return { allowed: false, reason: "VALIDATION_GATE_BYPASSED" };
    if (step === 9 && state.reviewState?.status !== "verified") return { allowed: false, reason: "VERIFICATION_GATE_BYPASSED" };
  }
  return { allowed: true, reason: "" };
}
export function moveWizard(state: ImportWizardState, target: ImportWizardStep) { const gate = gateForStep(state, target); return gate.allowed ? { state: touch({ ...state, currentStep: target }), reason: "" } : { state: { ...state, errors: [gate.reason] }, reason: gate.reason }; }
export async function extractFixture(state: ImportWizardState, fail = false): Promise<ImportWizardState> { if (fail) return touch({ ...state, errors: ["EXTRACTION_FAILED"], sourceDocument: state.sourceDocument ? { ...state.sourceDocument, extractionStatus: "failed" } : null }); try { const file = createImportFixtureFile(), bundle = await ingestSourceDocument({ file, metadata: { documentId: `${state.wizardId}-document`, sourceId: `${state.wizardId}-source`, title: state.metadata.title, sourceType: state.metadata.sourceType, publisher: state.metadata.publisher, edition: state.metadata.edition, curriculumYear: state.metadata.curriculumYear, gradeRange: state.metadata.gradeRange }, extractor: new FixtureDocumentExtractor(), storage: new LocalSourceStorage(), now: NOW }); return touch({ ...state, sourceDocument: bundle.document, extractedPages: bundle.pages, originalNormalizedText: Object.fromEntries(bundle.pages.map((page) => [String(page.pageNumber), page.normalizedText])), chunks: bundle.chunks, errors: [] }); } catch (error) { return touch({ ...state, errors: [error instanceof Error ? error.message : "EXTRACTION_FAILED"] }); } }
export function editNormalizedPage(state: ImportWizardState, pageNumber: number, text: string) { return touch({ ...state, extractedPages: state.extractedPages.map((page) => page.pageNumber === pageNumber ? { ...page, normalizedText: text, warnings: [...new Set([...page.warnings, "MANUALLY_EDITED"])] } : page) }); }
export function cancelNormalizedPageEdit(state: ImportWizardState, pageNumber: number) { const original = state.originalNormalizedText[String(pageNumber)]; return original === undefined ? state : editNormalizedPage(state, pageNumber, original); }
export function approvePage(state: ImportWizardState, pageNumber: number) { return touch({ ...state, approvedPageNumbers: [...new Set([...state.approvedPageNumbers, pageNumber])] }); }
export function rebuildChunks(state: ImportWizardState) { if (!state.sourceDocument) return state; const chunks = new FixtureDocumentExtractor().createChunks(state.sourceDocument, state.extractedPages).map((chunk) => ({ ...chunk, status: "reviewed" as const })); return touch({ ...state, chunks }); }
export function splitChunk(state: ImportWizardState, chunkId: string, offset?: number) { const index = state.chunks.findIndex((chunk) => chunk.chunkId === chunkId); if (index < 0) return state; const chunk = state.chunks[index], at = Math.max(1, Math.min(offset ?? Math.floor(chunk.normalizedText.length / 2), chunk.normalizedText.length - 1)); const parts = [chunk.normalizedText.slice(0, at).trim(), chunk.normalizedText.slice(at).trim()].filter(Boolean).map((text, part) => ({ ...chunk, chunkId: `${chunk.chunkId}-part-${part + 1}`, normalizedText: text, tokenEstimate: Math.ceil(text.length / 3), status: "reviewed" as const })); return touch({ ...state, chunks: [...state.chunks.slice(0, index), ...parts, ...state.chunks.slice(index + 1)] }); }
export function mergeChunks(state: ImportWizardState, firstId: string, secondId: string) { const first = state.chunks.find((item) => item.chunkId === firstId), second = state.chunks.find((item) => item.chunkId === secondId); if (!first || !second || first.documentId !== second.documentId) return state; const ranges = [...new Set(`${first.pageRange},${second.pageRange}`.split(","))].sort(); const merged: IngestionSourceChunk = { ...first, chunkId: `${first.chunkId}-merged`, pageRange: ranges.join(","), normalizedText: `${first.normalizedText}\n\n${second.normalizedText}`, rawText: `${first.rawText}\n\n${second.rawText}`, tokenEstimate: first.tokenEstimate + second.tokenEstimate, candidateTypes: [...new Set([...first.candidateTypes, ...second.candidateTypes])], reason: [...new Set([...first.reason, ...second.reason])], status: "reviewed" }; return touch({ ...state, chunks: state.chunks.filter(({ chunkId }) => chunkId !== firstId && chunkId !== secondId).concat(merged) }); }
export function updateChunk(state: ImportWizardState, chunkId: string, input: { heading?: string; candidateTypes?: CandidateType[]; status?: IngestionSourceChunk["status"] }) { return touch({ ...state, chunks: state.chunks.map((chunk) => chunk.chunkId === chunkId ? { ...chunk, ...input } : chunk) }); }
function conceptsFor(text: string) { if (/형태소/.test(text)) return ["morpheme"]; if (/단어/.test(text)) return ["word"]; if (/명사|대명사/.test(text)) return ["noun", "pronoun"]; if (/조사/.test(text)) return ["particle"]; return ["parts-of-speech"]; }
export function createWizardReviewQueue(state: ImportWizardState) { if (!state.sourceDocument) return state; const reviewItems = createReviewItems(state.sourceDocument, state.chunks).map((item) => ({ ...item, proposedConceptIds: conceptsFor(item.proposedContent) })); return touch({ ...state, reviewItems }); }
export function decideWizardReview(state: ImportWizardState, reviewItemId: string, decision: Exclude<ReviewDecision, "pending">, note = "", edited?: string) { return touch({ ...state, reviewItems: state.reviewItems.map((item) => item.reviewItemId === reviewItemId ? decideReviewItem(item, decision, note, edited) : item) }); }
export function createWizardDraft(state: ImportWizardState, base = authoringSamplePack) { if (!state.sourceDocument || state.reviewItems.some(({ status }) => status === "pending")) return { state: { ...state, errors: ["PENDING_REVIEW_IMPORTED"] }, reason: "PENDING_REVIEW_IMPORTED" }; const applied = applyReviewedItemsToDraft(base, state.reviewItems, state.sourceDocument); const pack = structuredClone(applied.pack); const noun = pack.concepts.find(({ conceptId }) => conceptId === "noun"); if (noun) noun.examples = noun.examples.slice(0, 5); return { state: touch({ ...state, draftPack: pack, conflicts: applied.conflicts, validationResult: null, coverageResult: [] }), reason: "" }; }
export function resolveWizardConflict(state: ImportWizardState, conflictId: string, resolution: "existing" | "proposed" | "merged") { const conflict = state.conflicts.find((item) => item.conflictId === conflictId); if (!conflict || !state.draftPack) return state; const pack = structuredClone(state.draftPack); if (resolution !== "existing") { const concept = pack.concepts.find(({ conceptId }) => conceptId === conflict.conceptId); if (concept && conflict.field === "definition.standard") concept.definition.standard = resolution === "proposed" ? conflict.proposedValue : `${conflict.existingValue} ${conflict.proposedValue}`; } const status: ContentConflict["status"] = resolution === "existing" ? "resolved_existing" : resolution === "proposed" ? "resolved_proposed" : "resolved_merged"; return touch({ ...state, draftPack: pack, conflicts: state.conflicts.map((item) => item.conflictId === conflictId ? { ...item, status } : item) }); }
export function repairFixtureCoverage(state: ImportWizardState) { if (!state.draftPack) return state; const pack = structuredClone(state.draftPack), noun = pack.concepts.find(({ conceptId }) => conceptId === "noun"), original = authoringSamplePack.concepts.find(({ conceptId }) => conceptId === "noun"); if (noun && original) noun.examples = structuredClone(original.examples); return touch({ ...state, draftPack: pack }); }
export function validateWizardDraft(state: ImportWizardState) { if (!state.draftPack) return state; return touch({ ...state, validationResult: validateAuthoringPack(state.draftPack), coverageResult: state.draftPack.concepts.map(calculateConceptCoverage) }); }
export function startWizardReview(state: ImportWizardState) { if (!state.draftPack || !state.validationResult?.valid || state.conflicts.some(({ status }) => status === "unresolved")) return { state: { ...state, errors: ["VALIDATION_GATE_BYPASSED"] }, reason: "VALIDATION_GATE_BYPASSED" }; const result = transitionPack(createPackWorkflow(state.draftPack, IMPORT_AUTHOR.actorId), "in_review", IMPORT_AUTHOR); return result.success ? { state: touch({ ...state, reviewState: result.workflow }), reason: "" } : { state, reason: result.reason }; }
export function completeWizardReview(state: ImportWizardState) { if (state.reviewState?.status !== "in_review") return { state, reason: "INVALID_PACK_STATUS_TRANSITION" }; const workflow = structuredClone(state.reviewState); workflow.checklists = workflow.pack.concepts.map(({ conceptId }) => completeChecklist(conceptId, IMPORT_REVIEWER.actorId)); const result = transitionPack(workflow, "reviewed", IMPORT_REVIEWER); return result.success ? { state: touch({ ...state, reviewState: result.workflow }), reason: "" } : { state, reason: result.reason }; }
export function requestWizardVerification(state: ImportWizardState) { if (state.reviewState?.status !== "reviewed") return { state, reason: "INVALID_PACK_STATUS_TRANSITION" }; const workflow = structuredClone(state.reviewState); workflow.pack.provenance = workflow.pack.provenance.map((item) => ({ ...item, verificationStatus: "reviewed", reviewedBy: IMPORT_REVIEWER.actorId, reviewedAt: NOW })); workflow.pack.concepts = workflow.pack.concepts.map((concept) => ({ ...concept, explanations: concept.explanations.map((item) => ({ ...item, status: "reviewed" })), examples: concept.examples.map((item) => ({ ...item, sourceStatus: "reviewed" })) })); const result = transitionPack(workflow, "verification_pending", IMPORT_VERIFIER); return result.success ? { state: touch({ ...state, reviewState: result.workflow }), reason: "" } : { state, reason: result.reason }; }
export function verifyWizardPack(state: ImportWizardState) { if (state.reviewState?.status !== "verification_pending") return { state, reason: "INVALID_PACK_STATUS_TRANSITION" }; const result = transitionPack(state.reviewState, "verified", IMPORT_VERIFIER); return result.success ? { state: touch({ ...state, reviewState: result.workflow, draftPack: result.workflow.pack }), reason: "" } : { state: { ...state, errors: [result.reason] }, reason: result.reason }; }
export function prepareWizardVerification(state: ImportWizardState) { const started = startWizardReview(state); if (started.reason) return started; const reviewed = completeWizardReview(started.state); if (reviewed.reason) return reviewed; const pending = requestWizardVerification(reviewed.state); if (pending.reason) return pending; return verifyWizardPack(pending.state); }
export function createWizardCandidate(state: ImportWizardState, notes = state.releaseNotes) { if (state.reviewState?.status !== "verified") return { state: { ...state, errors: ["VERIFICATION_GATE_BYPASSED"] }, reason: "VERIFICATION_GATE_BYPASSED" }; try { const releaseCandidate = createReleaseCandidate(state.reviewState, IMPORT_PUBLISHER, notes); return { state: touch({ ...state, releaseCandidate, releaseNotes: notes }), reason: "" }; } catch (error) { const reason = error instanceof Error ? error.message : "CANDIDATE_FAILED"; return { state: { ...state, errors: [reason] }, reason }; } }
export function wizardProgress(state: ImportWizardState) { const pages = state.extractedPages.length ? state.approvedPageNumbers.length / state.extractedPages.length : 0; const chunks = state.chunks.length ? state.chunks.filter(({ status }) => status === "reviewed" || status === "rejected").length / state.chunks.length : 0; const reviews = state.reviewItems.length ? state.reviewItems.filter(({ status }) => status !== "pending").length / state.reviewItems.length : 0; const coverage = state.coverageResult.length ? state.coverageResult.reduce((sum, item) => sum + item.score, 0) / state.coverageResult.length / 100 : 0; const checklist = state.reviewState?.checklists.length ? state.reviewState.checklists.filter(({ completed }) => completed).length / state.reviewState.checklists.length : 0; return { overall: Math.round((pages + chunks + reviews + coverage + checklist) / 5 * 100), pages, chunks, reviews, coverage, checklist }; }
