import "server-only";
import { createHash, createHmac, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import type { AdminSecurityStore } from "./types";
const scrypt = promisify(scryptCallback); export const ADMIN_SESSION_COOKIE = "hanip_admin_session"; export const ADMIN_SESSION_MS = 30 * 60_000;
const digest = (value: string) => createHash("sha256").update(value).digest("hex"); const sign = (value: string, secret: string) => createHmac("sha256", secret).update(value).digest("base64url");
export async function hashAdministratorPassword(password: string, pepper: string) { if (password.length < 8 || !pepper) throw new Error("invalid_admin_password"); const salt = randomBytes(16); const value = await scrypt(`${password}:${pepper}`, salt, 32) as Buffer; return `scrypt-admin-v1$${salt.toString("base64url")}$${value.toString("base64url")}`; }
export async function verifyAdministratorPassword(password: string, stored: string, pepper: string) { const [version,salt,hash]=stored.split("$"); if (version!=="scrypt-admin-v1"||!salt||!hash||password.length<8||!pepper)return false; try { const expected=Buffer.from(hash,"base64url"); const actual=await scrypt(`${password}:${pepper}`,Buffer.from(salt,"base64url"),expected.length) as Buffer; return expected.length===actual.length&&timingSafeEqual(expected,actual); } catch{return false;} }
const COMMON_ADMIN_PASSWORDS=new Set(["password","password1","admin123","administrator","qwerty123","12345678","123456789","hanip1234"]);
export function isAcceptableAdministratorPassword(password:string,adminId:string){const normalized=password.trim().toLowerCase();return password.length>=8&&normalized!==adminId.trim().toLowerCase()&&!COMMON_ADMIN_PASSWORDS.has(normalized)&&!/(.)\1{5,}/.test(password);}
export async function issueAdminSession(adminId:string,secret:string,store:AdminSecurityStore,now=Date.now()){if(!secret)throw new Error("admin_session_not_configured");const id=randomBytes(18).toString("base64url"),token=randomBytes(32).toString("base64url");await store.saveSession({id,adminId,tokenHash:digest(token),createdAt:new Date(now).toISOString(),expiresAt:new Date(now+ADMIN_SESSION_MS).toISOString(),revokedAt:null});const payload=`${id}.${token}`;return `${payload}.${sign(payload,secret)}`;}
export async function verifyAdminSession(cookie:string,secret:string,store:AdminSecurityStore,now=Date.now()){const[id,token,signature]=cookie.split(".");if(!id||!token||!signature||!secret)return null;const expected=Buffer.from(sign(`${id}.${token}`,secret)),actual=Buffer.from(signature);if(expected.length!==actual.length||!timingSafeEqual(expected,actual))return null;const record=await store.getSession(id);if(!record||record.revokedAt||Date.parse(record.expiresAt)<=now||record.tokenHash!==digest(token))return null;return record;}
export function adminTargetHash(value:string){return digest(value);}
