"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppHeader } from "@/components/ui/AppHeader";
import { LoadingSkeleton, PageContainer, SectionHeader } from "@/components/ui";
import { getAuthSession } from "@/lib/auth/authSession";
import type { AuthSessionState } from "@/lib/auth/types";
import { getLocalLearningRepository } from "@/lib/repository/repositoryFactory";
import type { LearningUserData } from "@/lib/repository/types";
import { applyUserSettings, loadUserSettings } from "@/lib/settings/settingsEngine";

export default function AccountClient() {
  const router = useRouter(); const [auth, setAuth] = useState<AuthSessionState>({ status: "loading", user: null, error: null }); const [data, setData] = useState<LearningUserData | null>(null);
  useEffect(() => { const session = getAuthSession(); const unsubscribe = session.subscribe(setAuth); void session.initialize().then((state) => { if (state.user) { setData(getLocalLearningRepository().loadUserDataSync(state.user.id)); applyUserSettings(loadUserSettings()); } }); return unsubscribe; }, []);
  async function signOut() { if (!window.confirm("로그아웃할까요? 저장된 학습 데이터는 삭제되지 않습니다.")) return; await fetch("/api/auth/logout", { method: "POST" }); await getAuthSession().signOut(); router.replace("/login"); router.refresh(); }
  if (auth.status === "loading") return <main className="min-h-screen bg-stone-50"><AppHeader subtitle="내 계정과 데이터"/><PageContainer className="py-10"><LoadingSkeleton label="계정 정보를 불러오고 있어요."/></PageContainer></main>;
  const concepts = data?.progress.concepts ?? []; const lastStudied = concepts.map(({ lastStudiedAt }) => lastStudiedAt).sort().at(-1);
  return <main className="min-h-screen bg-stone-50 text-stone-950"><AppHeader subtitle="내 계정과 데이터"/><PageContainer className="py-8 sm:py-10"><div className="mx-auto max-w-2xl"><SectionHeader title="계정" description="내 학습 기록과 개인정보 요청을 관리해요."/><section className="surface-card mt-6 p-5 sm:p-7"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-full bg-emerald-100 text-lg font-black text-emerald-900" aria-hidden="true">{(auth.user?.displayName || "학").slice(0, 1)}</div><div><p className="text-sm text-stone-500">닉네임</p><h2 className="text-xl font-bold">{auth.user?.displayName || "학생"}</h2></div></div><dl className="mt-6 grid gap-4 rounded-xl bg-stone-50 p-4 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">계정 생성일</dt><dd className="mt-1 font-bold">{auth.user?.createdAt ? new Date(auth.user.createdAt).toLocaleDateString("ko-KR") : "확인할 수 없음"}</dd></div><div><dt className="text-stone-500">저장된 학습</dt><dd className="mt-1 font-bold">{data?.sessions.length ?? 0}개 세션</dd></div><div><dt className="text-stone-500">학습 중인 개념</dt><dd className="mt-1 font-bold">{concepts.filter(({ status }) => status === "learning" || status === "needs_review").length}개</dd></div><div><dt className="text-stone-500">마지막 학습</dt><dd className="mt-1 font-bold">{lastStudied ? new Date(lastStudied).toLocaleString("ko-KR") : "아직 기록이 없어요."}</dd></div></dl><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/account/data" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-stone-300 bg-white px-4 font-semibold hover:bg-stone-100">내 학습 데이터 열람</Link><Link href="/settings" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-stone-300 bg-white px-4 font-semibold hover:bg-stone-100">학습 설정</Link><button onClick={() => void signOut()} className="min-h-12 rounded-xl bg-stone-950 px-4 font-semibold text-white sm:col-span-2">로그아웃</button></div></section><section className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="text-lg font-bold text-red-950">계정 및 데이터 관리</h2><p className="mt-2 text-sm leading-6 text-red-900">대화 삭제나 계정 삭제는 로그아웃과 달라요. 본인 확인 후 복구할 수 없는 데이터가 삭제될 수 있습니다.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/account/data" className="inline-flex min-h-12 items-center rounded-xl border border-red-300 bg-white px-4 font-semibold text-red-900">대화 삭제 요청</Link><Link href="/account/delete" className="inline-flex min-h-12 items-center rounded-xl bg-red-800 px-4 font-semibold text-white">계정 삭제 요청</Link></div></section></div></PageContainer></main>;
}
