"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppHeader } from "@/components/ui/AppHeader";
import { InlineNotice, LoadingSkeleton, PageContainer, PrimaryButton, SectionHeader } from "@/components/ui";
import { getAuthSession } from "@/lib/auth/authSession";
import { loadUserSettings, normalizeUserSettings, resetUserSettings, saveUserSettings } from "@/lib/settings/settingsEngine";
import type { UserSettings } from "@/lib/settings/types";
export default function SettingsClient() {
  const [saved, setSaved] = useState<UserSettings | null>(null); const [draft, setDraft] = useState<UserSettings | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { void getAuthSession().initialize().then(() => { const value = loadUserSettings(); setSaved(value); setDraft(value); }); }, []);
  const dirty = useMemo(() => Boolean(saved && draft && JSON.stringify(saved) !== JSON.stringify(draft)), [saved, draft]);
  function update(patch: Partial<UserSettings>) { setDraft((value) => value ? normalizeUserSettings({ ...value, ...patch, updatedAt: value.updatedAt }) : value); setNotice(""); }
  function save() { try { const value = saveUserSettings(draft!); setSaved(value); setDraft(value); setNotice("설정을 저장했어요."); } catch { setNotice("설정을 저장하지 못했어요. 기존 설정은 유지됩니다."); } }
  function reset() { if (!window.confirm("설정을 기본값으로 초기화할까요? 학습 기록은 유지됩니다.")) return; const value = resetUserSettings(); setSaved(value); setDraft(value); setNotice("기본 설정으로 초기화했어요."); }
  if (!draft) return <main className="min-h-screen bg-stone-50"><AppHeader subtitle="나에게 맞는 학습 환경"/><PageContainer className="py-10"><LoadingSkeleton label="설정을 불러오고 있어요."/></PageContainer></main>;
  return <main className="min-h-screen bg-stone-50 text-stone-950"><AppHeader subtitle="나에게 맞는 학습 환경"/><PageContainer className="py-8 sm:py-10"><div className="mx-auto max-w-2xl"><SectionHeader title="설정" description="읽기 편한 화면과 답하는 방식을 선택할 수 있어요."/><section className="surface-card mt-6 divide-y divide-stone-100 p-5 sm:p-7">
    <label className="block pb-5 text-sm font-bold">한잎 튜터 이름<span className="mt-1 block font-normal text-stone-500">대화 화면에서 부를 이름이에요.</span><input value={draft.tutorName} onChange={(e) => update({ tutorName: e.target.value })} maxLength={20} className="mt-3 min-h-12 w-full rounded-xl border border-stone-300 bg-white px-4 font-normal focus:border-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-100" /></label>
    <label className="block py-5 text-sm font-bold">답하는 방식<select value={draft.preferredInputMode} onChange={(e) => update({ preferredInputMode: e.target.value as UserSettings["preferredInputMode"] })} className="mt-3 min-h-12 w-full rounded-xl border border-stone-300 bg-white px-4 font-normal"><option value="balanced">선택지와 직접 입력을 함께</option><option value="choice_preferred">선택지를 더 자주</option><option value="free_input_preferred">직접 입력을 더 자주</option></select></label>
    <label className="block py-5 text-sm font-bold">글자 크기<select value={draft.textSize} onChange={(e) => update({ textSize: e.target.value as UserSettings["textSize"] })} className="mt-3 min-h-12 w-full rounded-xl border border-stone-300 bg-white px-4 font-normal"><option value="small">작게</option><option value="medium">기본</option><option value="large">크게</option></select></label>
    <div className="space-y-4 pt-5">{([["reducedMotion", "모션 줄이기", "움직이는 효과를 최소화해요."], ["showLearningStatus", "학습 상태 표시", "현재 목표와 미션을 대화 위에 보여 줘요."], ["showSuggestedReplies", "선택지 표시", "답하기 쉬운 선택지를 함께 보여 줘요."]] as const).map(([key, label, description]) => <label key={key} className="flex min-h-12 items-center justify-between gap-4 text-sm"><span><strong>{label}</strong><span className="mt-1 block text-stone-500">{description}</span></span><input type="checkbox" checked={draft[key]} onChange={(e) => update({ [key]: e.target.checked })} className="size-6 accent-emerald-800" /></label>)}</div>
  </section>{notice && <div className="mt-4"><InlineNotice tone={notice.includes("못") ? "error" : "success"}>{notice}</InlineNotice></div>}<div className="mt-5 flex flex-wrap gap-3"><PrimaryButton disabled={!dirty} onClick={save}>설정 저장</PrimaryButton><button onClick={reset} className="min-h-12 rounded-xl border border-stone-300 bg-white px-4 font-semibold hover:bg-stone-100">기본값으로 초기화</button></div><nav aria-label="정책 및 도움" className="mt-8 grid gap-3 border-t border-stone-200 pt-6 text-sm sm:grid-cols-3"><Link href="/privacy" className="min-h-12 rounded-xl bg-white p-4 font-semibold">개인정보 처리방침</Link><Link href="/terms" className="min-h-12 rounded-xl bg-white p-4 font-semibold">이용약관</Link><div className="rounded-xl bg-white p-4"><strong>문의처</strong><p className="mt-1 text-stone-600">동신중학교 정보교육 담당(정경원)</p></div></nav></div></PageContainer></main>;
}
